import { env } from "cloudflare:workers";
import Script from "next/script";
import { getManagerSession } from "../../manager-auth";
export const dynamic="force-dynamic";
type Feedback={id:string;customer_name:string|null;customer_email:string|null;message:string;contact_requested:number;severity:string;status:string;contacted_at:string|null;internal_note:string|null;created_at:string};
type Review={id:string;reviewer_name:string|null;rating:number;comment:string|null;google_created_at:string;reply_comment:string|null;reply_status:string};

export default async function OwnerPortal({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<Record<string,string|undefined>>}){
  const {slug}=await params,query=await searchParams,session=await getManagerSession();
  if(!session)return <SignIn slug={slug}/>;
  if(session.businessSlug!==slug)return <main className="manager-denied"><h1>Access restricted</h1><p>This account cannot access another business.</p></main>;
  if(!env.DB)throw new Error("Database unavailable");
  const days=new Set(["7","30","90"]).has(query.range??"")?Number(query.range):7,since=new Date(Date.now()-days*86400000).toISOString();
  const [feedbackResult,reviewsResult,eventResult,connection,setup]=await Promise.all([
    env.DB.prepare("SELECT * FROM feedback WHERE business_id=? ORDER BY CASE WHEN status='new' THEN 0 ELSE 1 END,created_at DESC LIMIT 100").bind(session.businessId).all<Feedback>(),
    env.DB.prepare("SELECT * FROM google_reviews WHERE business_id=? ORDER BY google_created_at DESC LIMIT 100").bind(session.businessId).all<Review>(),
    env.DB.prepare("SELECT event_type,COUNT(*) count FROM events WHERE business_id=? AND created_at>=? GROUP BY event_type").bind(session.businessId,since).all<{event_type:string;count:number}>(),
    env.DB.prepare("SELECT status,last_synced_at FROM google_connections WHERE business_id=?").bind(session.businessId).first<{status:string;last_synced_at:string|null}>(),
    env.DB.prepare("SELECT business_details_complete,manager_account_active,google_connection_tested,customer_page_approved,nfc_tested,qr_tested,private_feedback_tested,notification_email_tested FROM onboarding_checks WHERE business_id=?").bind(session.businessId).first<Record<string,number>>()
  ]);
  const feedback=feedbackResult.results,reviews=reviewsResult.results,counts=Object.fromEntries(eventResult.results.map(x=>[x.event_type,x.count]));
  const periodFeedback=feedback.filter(x=>x.created_at>=since),periodReviews=reviews.filter(x=>x.google_created_at>=since),waiting=feedback.filter(x=>x.contact_requested&&!x.contacted_at&&x.status!=="resolved"),flagged=feedback.filter(x=>x.severity!=="normal"&&x.status!=="resolved"),pending=reviews.filter(x=>x.reply_status!=="published");
  const setupDone=setup?Object.values(setup).filter(Boolean).length:0,attention=new Set([...waiting,...flagged].map(x=>x.id)),visible=query.view==="attention"?feedback.filter(x=>attention.has(x.id)):feedback;
  return <><link rel="stylesheet" href="/manager.css"/><link rel="stylesheet" href="/manager-extra.css"/><link rel="stylesheet" href="/owner-nav.css"/><main className="manager-shell">
    {query.from==="admin"&&<a className="back-to-admin" href={`/admin?business=${slug}`}>← Back to business portal</a>}
    <header className="manager-header"><a className="manager-brand" href={`/manager/${slug}`}><span>✓</span>streetvouch</a><nav className="manager-nav"><a className="active" href={`/manager/${slug}`}>Overview</a><a href="#feedback">Private messages</a><a href="#reviews">Google reviews</a><a href={`/manager/${slug}/onboarding`}>Setup</a></nav><div><span>{session.businessName}</span><form action="/api/manager/logout" method="post"><button>Sign out</button></form></div></header>
    <section className="manager-hero compact"><div><span className="kicker">OWNER PORTAL</span><h1>Your customer pulse.</h1><p>Review private messages, reply to Google reviews and see what needs attention.</p></div><div className="hero-actions"><form method="get"><label htmlFor="range">Showing</label><select id="range" name="range" defaultValue={String(days)}><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></select><button>Apply</button></form><button id="manager-send-summary" className="manager-secondary">Email summary</button></div></section>
    <p id="manager-status" className="manager-status" role="status"></p>
    {setupDone<8&&<section className="manager-card setup-callout"><div><span className="kicker">SETUP &amp; INTEGRATIONS</span><h2>{setupDone}/8 checks complete</h2><p>Finish connecting Google, approve the customer page and complete the launch checks.</p></div><a className="manager-primary" href={`/manager/${slug}/onboarding`}>Continue setup</a></section>}
    <section className="manager-metrics"><article><b>{counts.page_view??0}</b><span>page visits</span></article><article><b>{counts.google_click??0}</b><span>Google clicks</span></article><article><b>{periodFeedback.length}</b><span>private messages</span></article><article><b>{periodReviews.length}</b><span>new Google reviews</span></article></section>
    <section className="manager-card action-queue"><div className="card-heading"><div><span className="kicker">DO THESE FIRST</span><h2>{waiting.length+flagged.length+pending.length===0?"You’re all caught up":"Needs attention"}</h2></div><strong className="queue-count">{waiting.length+flagged.length+pending.length}</strong></div><div className="queue-items"><a href="#feedback"><b>{waiting.length}</b><span>customers waiting for a reply</span></a><a href="#feedback"><b>{flagged.length}</b><span>flagged messages</span></a><a href="#reviews"><b>{pending.length}</b><span>reviews without a reply</span></a></div></section>
    <section className="manager-grid"><article className="manager-card google-card"><span className="kicker">GOOGLE BUSINESS PROFILE</span><h2>{connection?.status==="connected"?"Reviews connected":"Connect Google reviews"}</h2><p>{connection?.status==="connected"?`Last checked ${connection.last_synced_at?new Date(connection.last_synced_at).toLocaleString("en-GB"):"recently"}.`:"Connect once to import reviews and publish approved replies."}</p><a className="manager-secondary" href={connection?.status==="connected"?"/api/google/sync":`/manager/${slug}/onboarding`}>{connection?.status==="connected"?"Sync now":"Finish setup"}</a></article><article className="manager-card report-card"><span className="kicker">EMAIL SUMMARY</span><h2>A clear overview.</h2><p>The email is a digest of new reviews, private feedback and items needing action. All detailed work stays here in the portal.</p></article></section>
    <section className="manager-content" id="feedback"><div className="content-heading"><div><span className="kicker">PRIVATE FEEDBACK</span><h2>Customer inbox</h2></div><nav className="simple-tabs"><a className={query.view!=="attention"?"active":""} href={`?range=${days}#feedback`}>All</a><a className={query.view==="attention"?"active":""} href={`?range=${days}&view=attention#feedback`}>Needs attention</a></nav></div>{visible.length===0?<div className="manager-empty">No private messages in this view.</div>:<div className="manager-list">{visible.map(item=><article className="manager-feedback" key={item.id}><div className="feedback-top"><span className={`severity ${item.severity}`}>{item.severity}</span><span>{item.status}</span><time>{new Date(item.created_at).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short"})}</time></div><p>{item.message}</p><div className="feedback-person"><span><b>{item.customer_name??"Anonymous"}</b>{item.customer_email&&<> · <a href={`mailto:${item.customer_email}`}>{item.customer_email}</a></>}</span>{item.contact_requested&&<strong>{item.contacted_at?"Customer contacted":"Reply requested"}</strong>}</div><label className="note-field">Private team note<textarea data-note-for={item.id} defaultValue={item.internal_note??""}/></label><div className="manager-actions"><button data-feedback-id={item.id} data-feedback-status="reviewed">Reviewed</button>{item.contact_requested&&!item.contacted_at&&<button data-feedback-id={item.id} data-feedback-action="contacted">Customer contacted</button>}<button data-feedback-id={item.id} data-feedback-status="resolved">Resolve</button><button data-feedback-id={item.id} data-feedback-action="note">Save note</button></div></article>)}</div>}</section>
    <section className="manager-content" id="reviews"><div className="content-heading"><div><span className="kicker">GOOGLE REVIEWS</span><h2>Review inbox</h2></div><span>{periodReviews.length} in this period</span></div>{reviews.length===0?<div className="manager-empty"><b>No Google reviews synced yet.</b><p>Connect Google in Setup and reviews will appear here.</p></div>:<div className="manager-list">{reviews.map(review=><article className="manager-feedback review-item" key={review.id}><div className="feedback-top"><span className="stars">{"★".repeat(review.rating)}{"☆".repeat(5-review.rating)}</span><span>{review.reply_status==="published"?"replied":"reply needed"}</span><time>{new Date(review.google_created_at).toLocaleDateString("en-GB")}</time></div><p>{review.comment??"Rating only"}</p><div className="feedback-person"><b>{review.reviewer_name??"Google customer"}</b></div>{review.reply_status==="published"?<div className="published-reply"><b>Your reply</b><p>{review.reply_comment}</p></div>:<form className="review-reply" data-review-id={review.id}><label>Reply<textarea defaultValue={review.rating>=4?"Thank you for your kind review. We really appreciate it and hope to see you again soon.":"Thank you for sharing this. We’re sorry your experience did not meet expectations. Please contact us so we can understand what happened."}/></label><button className="manager-primary" type="submit">Publish reply</button><span role="status"></span></form>}</article>)}</div>}</section>
  </main><Script src="/manager.js" strategy="afterInteractive"/></>;
}

function SignIn({slug}:{slug:string}){return <><link rel="stylesheet" href="/manager.css"/><main className="manager-login"><div className="login-brand"><span>✓</span>streetvouch</div><div className="login-card"><span className="kicker">BUSINESS OWNER PORTAL</span><h1>Sign in.</h1><p>Access your private messages, Google reviews, analysis and account setup.</p><form id="business-manager-login" data-slug={slug}><label>Email address<input id="business-login-email" type="email" required autoComplete="email"/></label><label>Password<input id="business-login-password" type="password" required autoComplete="current-password"/></label><button>Sign in</button><p id="login-status" role="status"></p></form></div></main><Script src="/manager-onboarding.js" strategy="afterInteractive"/></>}
