"use client";
import { useEffect,useRef,useState,type FormEvent } from "react";
import { LayoutDashboard,Building2,Inbox,Flag,BarChart3,Activity,Settings,Search,ArrowUpRight,ChevronRight,Check,Plus,RefreshCw,MessageSquare,Star,Menu,X } from "lucide-react";
type Row=Record<string,any>;
const date=(s:string)=>s?new Date(s).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'}):'Not yet';
const label=(s:string)=>String(s??'Not set').replaceAll('_',' ');
const navigation=[['overview','Overview',LayoutDashboard],['businesses','Businesses',Building2],['inbox','Unified inbox',Inbox],['reviews','Google reviews',Star],['attention','Needs attention',Flag],['reports','Reports',BarChart3],['health','System health',Activity],['settings','Settings',Settings]] as const;
const tabs=[['overview','Overview'],['inbox','Private feedback'],['reviews','Google reviews'],['analysis','Analysis'],['performance','Performance'],['customer','Customer page'],['assets','NFC / QR assets'],['setup','Setup & integrations'],['reports','Reports'],['activity','Activity log'],['access','Account & access']];
export default function Workspace(){
 const [route,setRoute]=useState<Row>({view:'overview'}),[data,setData]=useState<Row|null>(null),[profile,setProfile]=useState<Row|null>(null),[choices,setChoices]=useState<Row[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[caseId,setCaseId]=useState(''),[create,setCreate]=useState(false),[mobile,setMobile]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{const read=()=>{const p=Object.fromEntries(new URLSearchParams(location.search));setRoute({view:'overview',...p});};read();addEventListener('popstate',read);return()=>removeEventListener('popstate',read);},[]);
 function refresh(){setLoading(true);setError('');setRevision(v=>v+1);}
 function go(next:Row){setLoading(true);setError('');const target={view:next.view??route.view,...next};const p=new URLSearchParams(Object.entries(target).filter(([,v])=>v!==''&&v!=null).map(([k,v])=>[k,String(v)]));history.pushState({},'',`/admin?${p}`);setRoute(target);setMobile(false);setNotice('');}
 useEffect(()=>{let active=true;const view=route.view==='business'?(route.tab==='inbox'||route.tab==='reviews'||route.tab==='reports'?route.tab:'profile'):route.view==='settings'?'health':route.view;const p=new URLSearchParams({...route,view});Promise.all([fetch(`/api/admin/workspace?${p}`).then(async r=>{const j=await r.json() as Row;if(!r.ok)throw Error(j.message);return j;}),route.business?fetch(`/api/admin/workspace?view=profile&business=${encodeURIComponent(route.business)}`).then(async r=>await r.json() as Row):Promise.resolve(null)]).then(([d,p])=>{if(active){setData(d);setProfile(p);}}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false;};},[route,revision]);
 useEffect(()=>{fetch('/api/admin/workspace?view=choices').then(async r=>await r.json() as Row).then(d=>setChoices(d.rows??[])).catch(()=>{});},[revision]);
 async function act(body:Row,url='/api/admin/workspace',method='POST'){setBusy(true);setNotice('');try{const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json() as Row;if(!r.ok)throw Error(j.message??'Action failed.');setNotice(j.message??'Saved.');refresh();return j;}catch(e){setNotice((e as Error).message);return null;}finally{setBusy(false);}}
 const view=route.view,tab=route.tab??'overview',business=profile?.business,effective=view==='business'?tab:view;
 const openBusiness=(id:string,t='overview')=>go({view:'business',business:id,tab:t});
 const filter=(f:string)=>go({...route,filter:f,page:1});
 const summary=data?.summary??{};
 const metrics=[['Active businesses',summary.active,'businesses','active'],['In setup',summary.setup,'businesses','setup'],['Businesses needing attention',summary.attention,'businesses','attention'],['New messages',summary.new_messages,'inbox','new'],['Awaiting reply',summary.waiting,'inbox','awaiting'],['Unanswered reviews',summary.unanswered,'reviews','unanswered'],['Urgent cases',summary.urgent,'inbox','urgent'],['Email delivery issues',(summary.failed_notifications??0)+(summary.failed_messages??0),'health','unhealthy'],['Google failures',summary.failed_google,'health','unhealthy'],['Reports due',summary.due_reports,'businesses','due'],['Reports sent · 7 days',summary.sent_reports,'reports','sent'],['Reports failed',summary.failed_reports,'reports','failed']];
 return <div className="op"><a className="op-skip" href="#op-main">Skip to workspace</a><aside className={`op-sidebar ${mobile?'open':''}`}><button className="op-mobile op-close-nav" aria-label="Close navigation" onClick={()=>setMobile(false)}><X size={20}/></button><a className="op-brand" href="/admin"><span><Check size={20}/></span>streetvouch</a><p className="op-caption">BUSINESS PORTAL</p><nav aria-label="Main navigation">{navigation.map(([key,name,Icon])=><a href={`/admin?view=${key}`} key={key} aria-current={view===key||view==='business'&&key==='businesses'?'page':undefined} onClick={e=>{e.preventDefault();go({view:key});}}><Icon size={18}/>{name}</a>)}</nav><div className="op-sidebar-foot"><span className="op-dot"/>Operator access<a href="/signout-with-chatgpt?return_to=%2Fadmin">Sign out <ArrowUpRight size={14}/></a></div></aside>
 <div className="op-body"><header className="op-topbar"><button className="op-mobile" aria-label="Toggle navigation" aria-expanded={mobile} onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><span>StreetVouch <ChevronRight size={14}/> {view==='business'?business?.name??'Business':navigation.find(x=>x[0]===view)?.[1]}</span><span className="op-private">Private workspace</span></header><main id="op-main"><div className="op-heading"><div><p className="op-eyebrow">{view==='business'?'BUSINESS WORKSPACE':'YOUR OPERATING WORKSPACE'}</p><h1>{view==='business'?business?.name??'Loading business…':navigation.find(x=>x[0]===view)?.[1]}</h1><p>{view==='overview'?'A clear view of your clients and the work that needs you.':view==='inbox'?'Private customer conversations, follow-up and internal notes.':view==='reviews'?'Imported Google reviews. Review every reply before publishing.':view==='businesses'?'Find a business, check its health and take the next step.':view==='health'?'Connection and delivery problems across your portfolio.':view==='reports'?'Email summaries and their recorded delivery outcomes.':view==='business'?`${label(business?.status)} · ${business?.category??'Local business'}`:''}</p></div><div className="op-actions"><button aria-label="Refresh workspace" onClick={refresh}><RefreshCw size={16}/></button>{view==='businesses'&&<button className="primary" onClick={()=>setCreate(true)}><Plus size={16}/>Add business</button>}</div></div>
 {notice&&<p className="op-notice" role="status">{notice}</p>}{error?<div className="op-empty" role="alert"><h2>Workspace unavailable</h2><p>{error}</p><button onClick={refresh}>Try again</button></div>:<>
 {view==='business'&&<nav className="op-tabs" aria-label="Business sections">{tabs.map(([key,name])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>go({view:'business',business:route.business,tab:key})}>{name}</button>)}</nav>}
 {loading?<div className="op-loading" role="status">Loading workspace…</div>:<>
 {(view==='overview'||view==='attention')&&<>{view==='overview'&&<div className="op-stats">{metrics.map(([name,count,v,f])=><button key={String(name)} onClick={()=>go({view:v,filter:f,...(name==='Reports sent · 7 days'?{from:new Date(Date.now()-7*86400000).toISOString().slice(0,10)}:{})})}><span>{name}</span><strong>{count??0}</strong><ArrowUpRight size={15}/></button>)}</div>}<div className="op-columns"><section className="op-panel"><div className="op-section-head"><h2>Needs attention</h2><span>Cases counted once</span></div>{data?.queue?.length?data.queue.map((r:Row)=><button className="op-queue" key={r.id} onClick={()=>setCaseId(r.id)}><span className={`op-priority ${r.severity==='serious'||r.status==='escalated'?'urgent':''}`}/><div><b>{r.business_name}</b><p>{r.severity==='serious'||r.status==='escalated'?'Escalate sensitive feedback':r.contact_requested&&!r.contacted_at?'Customer is waiting for a reply':'Review new customer feedback'}</p><small>{r.assignee??'Unassigned'} · {date(r.created_at)}{r.due_at?` · Due ${date(r.due_at)}`:''}</small></div><ChevronRight size={18}/></button>):<Empty title="No open cases" text="New or unresolved customer cases will appear here."/>}<div className="op-panel-foot"><button onClick={()=>go({view:'inbox'})}>Open unified inbox →</button></div></section><section className="op-panel"><div className="op-section-head"><h2>Recent activity</h2></div><ActivityList rows={data?.activity??[]}/></section></div><section className="op-panel"><div className="op-section-head"><h2>Business watchlist</h2><button onClick={()=>go({view:'businesses',filter:'attention'})}>View all →</button></div><BusinessTable rows={(data?.rows??[]).filter((r:Row)=>r.work+r.unanswered+r.failed_notifications+r.failed_messages+r.failed_reports+r.report_due>0||['sync_failed','reauthorisation_required','needs_attention'].includes(r.google_status)).slice(0,8)} open={openBusiness}/></section></>}
 {(['businesses','inbox','reviews','reports','health'].includes(effective))&&<><form className="op-filters" key={JSON.stringify(route)} onSubmit={e=>{e.preventDefault();go({...route,...Object.fromEntries(new FormData(e.currentTarget)),page:1});}}>{effective!=='health'&&<label className="op-search"><Search size={16}/><input name="q" aria-label="Search records" defaultValue={route.q??''} placeholder="Search records…"/></label>}{view!=='business'&&['inbox','reviews','reports'].includes(effective)&&<select name="business" aria-label="Business" defaultValue={route.business??''}><option value="">All businesses</option>{choices.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>}<select name="filter" aria-label="Filter" defaultValue={route.filter??'all'}>{(effective==='businesses'?['all','active','setup','awaiting_approval','paused','completed','attention','unhealthy','due']:effective==='inbox'?['all','new','awaiting','attention','urgent','resolved','failed']:effective==='reviews'?['all','unanswered','negative','recent','replied']:effective==='reports'?['all','sent','failed']:['all','unhealthy']).map(x=><option value={x} key={x}>{label(x)}</option>)}</select>{effective==='businesses'?<><select name="google" aria-label="Google connection" defaultValue={route.google??''}><option value="">Any Google status</option><option value="connected">Connected</option><option value="disconnected">Not connected</option></select><select name="sort" aria-label="Sort businesses" defaultValue={route.sort??'urgency'}>{['urgency','name','activity','setup','performance'].map(x=><option key={x}>{x}</option>)}</select></>:effective!=='health'&&<><label>From<input name="from" type="date" defaultValue={route.from??''}/></label><label>To<input name="to" type="date" defaultValue={route.to??''}/></label></>}<button type="submit">Apply</button></form>
 {effective==='businesses'&&<section className="op-panel"><BusinessTable rows={data?.rows??[]} open={openBusiness}/></section>}
 {effective==='inbox'&&<section className="op-panel"><div className="op-table-wrap"><table><thead><tr><th>Customer / business</th><th>Message</th><th>Next action</th><th>Owner</th><th>Received</th></tr></thead><tbody>{data?.rows?.map((r:Row)=><tr key={r.id}><td><button className="op-link" onClick={()=>setCaseId(r.id)}>{r.customer_name??'Anonymous customer'}</button><small>{r.business_name}</small></td><td className="op-excerpt">{r.message}</td><td><Status value={r.status}/><small>{r.contact_requested?(r.contacted_at?'Contact recorded':'Reply requested'):'No contact requested'}</small>{r.severity==='serious'&&<strong className="op-danger">Urgent review</strong>}</td><td>{r.assignee??'Unassigned'}<small>{r.due_at?`Due ${date(r.due_at)}`:''}</small></td><td>{date(r.created_at)}</td></tr>)}</tbody></table></div>{!data?.rows?.length&&<Empty title="No messages match" text="Try another filter or wait for customer feedback."/>}</section>}
 {effective==='reviews'&&<><p className="op-muted">Reviews may arrive directly through Google Search or Maps. These counts do not measure reviews generated by StreetVouch.</p><section className="op-panel">{data?.rows?.map((r:Row)=><Review key={r.id} row={r} act={act} busy={busy}/>)}{!data?.rows?.length&&<Empty title="No reviews to show" text="Connect Google in the owner portal and sync the business to import its reviews."/>}</section></>}
 {effective==='reports'&&<section className="op-panel">{view==='business'&&<div className="op-section-head"><h2>Weekly email summaries</h2><button disabled={busy} onClick={()=>{if(confirm('Generate and email a weekly summary to this business’s configured recipient?'))act({businessId:route.business},'/api/admin/reports');}}>Send weekly summary</button></div>}{data?.rows?.map((r:Row)=><details className="op-record" key={r.id}><summary><b>{r.business_name}</b><span>{r.recipient_email}</span><Status value={r.status}/><time>{date(r.created_at)}</time></summary><p>{date(r.period_start)} – {date(r.period_end)}</p>{r.error&&<p className="op-danger">{r.error}</p>}<ReportSnapshot snapshot={r.snapshot}/>{r.status==='failed'&&<button disabled={busy} onClick={()=>{if(confirm('Retry this failed report to its recorded recipient?'))act({businessId:r.business_id,reportId:r.id},'/api/admin/reports');}}>Retry failed report</button>}</details>)}{!data?.rows?.length&&<Empty title="No email summaries yet" text="Generate a summary from an individual business’s Reports section."/>}<p className="op-footnote">Sent means accepted by the email provider. Inbox delivery is not confirmed here.</p></section>}
 {effective==='health'&&<><div className="op-health-summary"><b>Database available</b><span>Email {data?.configured?.email?'configured':'not configured'}</span><span>Google credentials {data?.configured?.google?'configured':'missing'}</span></div><section className="op-panel">{data?.rows?.map((r:Row)=><div className="op-health-row" key={r.id}><div><button className="op-link" onClick={()=>openBusiness(r.id,'setup')}>{r.name}</button><p>Google: {label(r.google_status)} · Last sync {date(r.last_synced_at)}</p>{r.last_error&&<p className="op-danger">{r.last_error}</p>}<small>{r.failed_notifications} alert issues · {r.failed_messages} reply issues · {r.failed_reports} report issues{r.report_due?' · Weekly summary due':''} · {r.assets} active assets{r.status==='active'&&!r.assets?' — customer entry points need checking':''}</small></div><button disabled={busy||!['connected','sync_failed'].includes(r.google_status)} onClick={()=>act({action:'sync',businessId:r.id})}>Retry sync</button></div>)}</section><form action="/api/admin/retry-notifications" method="post" onSubmit={e=>{if(!confirm('Retry up to 25 failed operator notifications?'))e.preventDefault();}}><button>Retry failed operator alerts</button></form><p className="op-footnote">Stale means no recorded sync in 24 hours. Physical asset condition requires an on-site check. Background activity is shown only when recorded.</p></>}
 <Pagination data={data} go={n=>go({...route,page:n})}/></>}
 {view==='settings'&&<section className="op-panel op-pad"><h2>Workspace access and services</h2><p>This portal is restricted to the configured StreetVouch operator. Business owners use their own accounts and cannot access this workspace.</p><dl className="op-facts"><dt>Email service</dt><dd>{data?.configured?.email?'Configured':'Not configured'}</dd><dt>Google integration</dt><dd>{data?.configured?.google?'Credentials configured':'Google approval and credentials are required'}</dd><dt>AI assistance</dt><dd>{data?.configured?.ai?'Configured':'Existing saved suggestions remain available; no new AI analysis is configured'}</dd></dl><p className="op-muted">Secrets and operator access are managed through protected hosting settings. Customer replies are sent only after your review and confirmation.</p></section>}
 {view==='business'&&profile&&!['inbox','reviews','reports'].includes(tab)&&<BusinessProfile profile={profile} tab={tab} act={act} busy={busy} open={openBusiness}/>}
 </>}</>}
 </main><footer className="op-footer">StreetVouch · Business operations <span>Private customer data stays within authorised accounts.</span></footer></div>
 {caseId&&<CasePanel id={caseId} close={()=>setCaseId('')} changed={refresh}/>}
 {create&&<Modal title="Add a business" close={()=>setCreate(false)}><form onSubmit={async e=>{e.preventDefault();const j=await act(Object.fromEntries(new FormData(e.currentTarget)),'/api/admin/businesses');if(j){setCreate(false);openBusiness(j.id,'setup');}}}><label>Business name<input name="name" required/></label><label>Owner contact email<input name="contactEmail" type="email" required/></label><label>Category<input name="category"/></label><label>Address<textarea name="address"/></label><button className="primary" disabled={busy}>Create business</button>{notice&&<p role="status">{notice}</p>}</form></Modal>}
 </div>;
}
function Empty({title,text}:{title:string;text:string}){return <div className="op-empty"><MessageSquare size={25}/><h3>{title}</h3><p>{text}</p></div>}
function Status({value}:{value:string}){return <span className={`op-status ${['failed','unknown','escalated','serious'].includes(value)?'danger':value==='active'||value==='sent'||value==='resolved'?'good':''}`}>{label(value)}</span>}
function Pagination({data,go}:{data:Row|null;go:(n:number)=>void}){return (data?.total??0)>40?<div className="op-pagination"><span>{data?.total} records · Page {data?.page}</span><button disabled={data?.page<=1} onClick={()=>go(data!.page-1)}>Previous</button><button disabled={data!.page*40>=data!.total} onClick={()=>go(data!.page+1)}>Next</button></div>:null}
function BusinessTable({rows,open}:{rows:Row[];open:(id:string,t?:string)=>void}){return rows.length?<div className="op-table-wrap"><table><thead><tr><th>Business</th><th>Status / setup</th><th>Open work</th><th>Google</th><th>Latest activity</th><th>Last email</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><button className="op-link" onClick={()=>open(r.id)}>{r.name}</button><small>{r.contact_email??r.owner_email??'Owner not assigned'}</small></td><td><Status value={r.status}/><small>{r.setup_done}/8 setup checks</small></td><td><b>{r.work} cases</b><small>{r.unanswered} reviews awaiting replies</small>{r.failed_notifications+r.failed_messages>0&&<small className="op-danger">Delivery issues need attention</small>}</td><td>{label(r.google_status)}<small>{date(r.last_synced_at)}</small></td><td>{date(r.last_activity)}</td><td>{date(r.last_report_sent_at)}</td></tr>)}</tbody></table></div>:<Empty title="No businesses match" text="Adjust the filters or add your first business."/>}
function ActivityList({rows}:{rows:Row[]}){return rows.length?<ol className="op-activity">{rows.map((a,i)=><li key={a.id??i}><b>{label(a.action)}</b><p>{a.business_name??a.actor_email??'System'}</p><small>{date(a.created_at)}</small>{a.detail&&<details><summary>Details</summary><p>{a.detail}</p></details>}</li>)}</ol>:<Empty title="No recorded activity" text="Meaningful operator actions will appear here."/>}
function ReportSnapshot({snapshot}:{snapshot:string}){let obj:Row={};try{obj=JSON.parse(snapshot??'{}');}catch{}return <dl className="op-facts">{Object.entries(obj).map(([k,v])=><div key={k}><dt>{k.replace(/([A-Z])/g,' $1')}</dt><dd>{typeof v==='object'?JSON.stringify(v):String(v??'No data')}</dd></div>)}</dl>}
function Review({row:r,act,busy}:{row:Row;act:(b:Row)=>Promise<any>;busy:boolean}){const[text,setText]=useState(r.suggested_reply??r.reply_comment??'');return <article className="op-review"><div className="op-section-head"><div><b>{r.business_name}</b><p><span className="op-stars">{'★'.repeat(Math.max(0,Math.min(5,r.rating)))}</span> {r.reviewer_name??'Google customer'} · {date(r.google_created_at)}</p></div><Status value={r.reply_status}/></div><p className="op-message">{r.comment??'Rating only'}</p>{r.reply_comment&&<blockquote><b>Published reply</b><p>{r.reply_comment}</p></blockquote>}<details><summary>{r.reply_status==='published'?'Edit published reply':'Draft a reply'}</summary><label>Public Google reply<textarea value={text} maxLength={4096} onChange={e=>setText(e.target.value)}/></label><div className="op-actions"><button disabled={busy||!text.trim()} onClick={()=>act({action:'review_draft',id:r.id,businessId:r.business_id,text})}>Save draft</button><button className="primary" disabled={busy||!text.trim()||r.google_status!=='connected'} onClick={()=>{if(confirm(`Publish this reply publicly on ${r.business_name}’s Google profile?`))act({action:'review_publish',id:r.id,businessId:r.business_id,text,confirmed:true});}}>Publish approved reply</button></div>{r.google_status!=='connected'&&<p className="op-danger">Google is disconnected. The owner must reconnect before publishing.</p>}</details></article>}
function Modal({title,children,close}:{title:string;children:React.ReactNode;close:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog aria-label={title} className="op-dialog" ref={ref} onCancel={e=>{e.preventDefault();close();}}><div className="op-section-head"><h2>{title}</h2><button onClick={close} aria-label="Close"><X size={20}/></button></div>{children}</dialog>}
function CasePanel({id,close,changed}:{id:string;close:()=>void;changed:()=>void}){
 const[data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[text,setText]=useState(''),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(){const r=await fetch(`/api/admin/workspace?case=${encodeURIComponent(id)}`),j=await r.json() as Row;if(!r.ok)throw Error(j.message);setData(j);return j;}
 useEffect(()=>{let active=true;fetch(`/api/admin/workspace?case=${encodeURIComponent(id)}`).then(async r=>{const j=await r.json() as Row;if(!r.ok)throw Error(j.message);return j;}).then(j=>{if(!active)return;setData(j);const m=j.messages.filter((m:Row)=>m.status==='draft').at(-1);if(m){setText(m.body);setDraft(m.id);}}).catch(e=>active&&setError(e.message));return()=>{active=false;};},[id]);
 async function action(body:Row){setBusy(true);try{const r=await fetch('/api/admin/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,id,businessId:data?.item.business_id})}),j=await r.json() as Row;setNotice(j.message);if(j.messageId)setDraft(j.messageId);await load();changed();return r.ok?j:null;}catch{setNotice('Could not confirm the action. Reload this case before retrying.');return null;}finally{setBusy(false);}}
 const f=data?.item;return <Modal title="Private feedback" close={close}>{error?<p role="alert">{error}</p>:!f?<p>Loading conversation…</p>:<><p className="op-eyebrow">{f.business_name}</p><div className="op-section-head"><h3>{f.customer_name??'Anonymous customer'}</h3><Status value={f.status}/></div><p>{f.customer_email??'No email supplied'} · {f.contact_requested?'Contact requested':'No contact requested'}</p><p className="op-muted">Received {date(f.created_at)}</p><blockquote className="op-message">{f.message}</blockquote>{f.severity==='serious'||f.status==='escalated'?<p className="op-warning">Sensitive case: involve the business owner. Do not promise compensation or an outcome without their approval.</p>:null}
 <form className="op-case-meta" key={`${f.status}-${f.assignee}-${f.due_at}`} onSubmit={e=>{e.preventDefault();action({action:'case',...Object.fromEntries(new FormData(e.currentTarget))});}}><label>Status<select name="status" defaultValue={f.status}>{['new','reviewed','attention','escalated','resolved'].map(s=><option key={s}>{s}</option>)}</select></label><label>Next action owner<input name="assignee" defaultValue={f.assignee??''} placeholder="Name or role"/></label><label>Due date<input type="date" name="dueAt" defaultValue={f.due_at?.slice(0,10)??''}/></label><button disabled={busy}>Update case</button></form>
 <section className="op-compose"><h3>Reply by email</h3><p className="op-muted">The customer’s response goes to the business contact email. Replies sent back by customers are not imported into this portal.</p>{data.analysis?.draft_reply&&<button onClick={()=>setText(data.analysis.draft_reply)}>Use saved {data.analysis.model==='streetvouch-rules-v1'?'suggested':'AI-assisted'} reply</button>}<label>Message to customer<textarea value={text} onChange={e=>{setText(e.target.value);}} maxLength={10000}/></label><div className="op-actions"><button disabled={busy||!text.trim()} onClick={()=>action({action:'draft',text,...(draft?{messageId:draft}:{})})}>Save draft</button><button className="primary" disabled={busy||!text.trim()||!f.customer_email||!f.contact_requested} onClick={async()=>{if(!confirm(`Send this private reply to ${f.customer_email}?`))return;const j=await action({action:'draft',text,...(draft?{messageId:draft}:{})});if(j){await action({action:'send',messageId:j.messageId,confirmed:true});setDraft('');setText('');}}}>Review & send reply</button><button disabled={busy} onClick={()=>action({action:'case',contacted:true,dueAt:f.due_at})}>Record contact elsewhere</button></div>{(!f.customer_email||!f.contact_requested)&&<p className="op-warning">Email reply unavailable: the customer must supply an email and request contact.</p>}</section>
 <details><summary>Add an internal note</summary><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const j=await action({action:'note',text:new FormData(form).get('note')});if(j)form.reset();}}><label>Operator-only note<textarea name="note" required maxLength={5000}/></label><button disabled={busy}>Save internal note</button></form></details>{notice&&<p className="op-notice" role="status">{notice}</p>}
 <h3>Conversation & history</h3>{f.internal_note&&<blockquote><b>Existing team note</b><p>{f.internal_note}</p></blockquote>}<ol className="op-activity">{[...data.messages.map((m:Row)=>({...m,event:'message'})),...data.audit.map((a:Row)=>({...a,event:'audit'}))].sort((a:Row,b:Row)=>a.created_at.localeCompare(b.created_at)).map((r:Row)=><li key={r.id}><b>{r.event==='message'?(r.kind==='note'?'Internal note — never emailed':`Email reply · ${r.status==='sent'?'provider accepted':label(r.status)}`):label(r.action)}</b><small>{date(r.created_at)} · {r.actor??r.actor_email}</small><p className="op-message">{r.body??r.detail}</p>{r.error&&<p className="op-danger">{r.error}</p>}{r.status==='failed'&&r.kind==='reply'&&<button onClick={()=>{setDraft('');setText(r.body);setNotice('Copied into a new draft. Check the failure before resending.');}}>Copy into a new draft</button>}{r.status==='draft'&&<button onClick={()=>{setDraft(r.id);setText(r.body);}}>Edit draft</button>}</li>)}</ol></>}</Modal>;
}
function BusinessProfile({profile:p,tab,act,busy,open}:{profile:Row;tab:string;act:(body:Row,url?:string,method?:string)=>Promise<any>;busy:boolean;open:(id:string,t?:string)=>void}){
 const b=p.business,s=p.setup??{},[result,setResult]=useState<Row|null>(null);const checks=[['business_details_complete','Business details','StreetVouch'],['manager_account_active','Owner account','Client'],['google_connection_tested','Google connection and sync','Client / StreetVouch'],['customer_page_approved','Customer page published','StreetVouch'],['nfc_tested','NFC destination tested','StreetVouch'],['qr_tested','QR destination tested','StreetVouch'],['private_feedback_tested','Private feedback tested','StreetVouch'],['notification_email_tested','Notification delivery tested','StreetVouch']];const done=checks.filter(([k])=>s[k]).length;
 async function form(e:FormEvent<HTMLFormElement>,url:string,extra:Row={},method='POST'){e.preventDefault();const j=await act({...Object.fromEntries(new FormData(e.currentTarget)),businessId:b.id,...extra},url,method);if(j)setResult(j);}
 return <><div className="op-business-tools"><a href={`/customer/${b.slug}/preview`} target="_blank" rel="noreferrer">Preview customer page <ArrowUpRight size={14}/></a><a href={`/manager/${b.slug}?from=admin`} target="_blank" rel="noreferrer">Open owner sign-in <ArrowUpRight size={14}/></a></div>
 {tab==='overview'&&<><section className="op-panel op-pad"><p className="op-eyebrow">NEXT RECOMMENDED ACTION</p><h2>{done<8?`Complete ${checks.find(([k])=>!s[k])?.[1].toLowerCase()}`:b.google_status!=='connected'?'Ask the owner to reconnect Google':'Check outstanding customer conversations'}</h2><p>{done<8?`${done} of 8 launch checks are recorded. Next owner: ${checks.find(([k])=>!s[k])?.[2]}.`:'Open the inbox and review unanswered messages before routine improvements.'}</p><button className="primary" onClick={()=>open(b.id,done<8||b.google_status!=='connected'?'setup':'inbox')}>Open next step →</button></section><div className="op-columns"><section className="op-panel op-pad"><h2>Operating status</h2><dl className="op-facts"><dt>Status</dt><dd><Status value={b.status}/></dd><dt>Google</dt><dd>{label(b.google_status)}</dd><dt>Unresolved feedback</dt><dd><button className="op-link" onClick={()=>open(b.id,'inbox')}>{b.open_cases} cases · {b.waiting} awaiting contact</button></dd><dt>Unanswered reviews</dt><dd><button className="op-link" onClick={()=>open(b.id,'reviews')}>{b.unanswered}</button></dd><dt>Delivery failures</dt><dd>{b.failed_alerts} alerts · {b.failed_reports} reports</dd><dt>Last sync</dt><dd>{date(b.last_synced_at)}</dd><dt>Active NFC / QR assets</dt><dd>{p.assets.filter((a:Row)=>a.active).length}</dd><dt>Last email summary</dt><dd>{date(b.last_report_sent_at)}</dd></dl>{b.last_error&&<p className="op-danger">{b.last_error}</p>}</section><section className="op-panel"><div className="op-section-head"><h2>Recent activity</h2></div><ActivityList rows={p.activity.slice(0,5)}/></section></div></>}
 {tab==='setup'&&<><section className="op-panel"><div className="op-section-head"><h2>Activation readiness</h2><span>{done}/8 checks</span></div>{checks.map(([key,name,owner],i)=><div className="op-check" key={key}><span className={s[key]?'complete':''}>{s[key]?<Check size={17}/>:i+1}</span><div><b>{name}</b><small>{owner} · {s[key]?'Complete':'Needs completion'}</small></div><button disabled={busy||['business_details_complete','manager_account_active','google_connection_tested','customer_page_approved'].includes(key)} onClick={()=>{if(confirm(`Confirm ${name.toLowerCase()} has ${s[key]?'to be repeated':'passed a real controlled test'}?`))act({businessId:b.id,action:'check',check:key,value:!s[key]},'/api/admin/onboarding');}}>{s[key]?'Reset check':'Confirm test'}</button></div>)}<div className="op-panel-foot"><p>Business details, the published customer page, owner account and Google checks are verified from actual records. Physical and delivery tests require operator confirmation.</p><button disabled={busy||!['connected','sync_failed'].includes(b.google_status)} onClick={()=>act({action:'sync',businessId:b.id})}>Test Google sync</button><button onClick={()=>open(b.id,'access')}>Owner access</button></div></section><details className="op-panel op-pad"><summary>Account lifecycle</summary><p>Activation requires every check and valid connected records. Pausing disables the managed customer entry points.</p><div className="op-actions">{['activate','pause','complete'].map(action=><button key={action} disabled={busy||action==='activate'&&done<8} onClick={()=>{if(confirm(`${label(action)} ${b.name}?`))act({businessId:b.id,action},'/api/admin/onboarding');}}>{label(action)} pilot</button>)}</div></details></>}
 {tab==='customer'&&<section className="op-panel op-pad"><h2>Business & customer-page details</h2><p className="op-muted">Save changes as a draft, preview them, then publish the page directly from this workspace. Owner approval is optional and does not block launch.</p><form className="op-detail-form" key={b.updated_at} onSubmit={e=>{const submitter=(e.nativeEvent as SubmitEvent).submitter as HTMLButtonElement|null;form(e,'/api/admin/businesses',{publishCustomerPage:submitter?.value==='publish'},'PATCH');}}>{[['name','Business name','name'],['category','Category','category'],['contactEmail','Contact email','contact_email'],['phone','Phone','phone'],['address','Address','address'],['website','Website','website'],['openingHours','Opening hours','opening_hours'],['logoUrl','Logo URL','logo_url'],['googleProfileUrl','Google profile URL','google_profile_url'],['googleReviewUrl','Google review URL','google_review_url'],['customerHeading','Customer heading','customer_heading'],['customerIntro','Introduction','customer_intro'],['customerPrivatePrompt','Private-feedback prompt','customer_private_prompt']].map(([name,title,key])=><label key={name}>{title}<input name={name} defaultValue={b[key]??''} required={['name','category','contactEmail','phone','address','googleProfileUrl'].includes(name)} type={name==='contactEmail'?'email':name.includes('Url')||name==='website'?'url':'text'}/></label>)}<div className="op-actions"><button disabled={busy} value="draft">Save draft</button><button className="primary" disabled={busy} value="publish">Save &amp; publish customer page</button></div></form></section>}
 {tab==='assets'&&<><section className="op-panel">{p.assets.map((a:Row)=><details className="op-record" key={a.id}><summary><b>{a.label}</b><span>{a.placement}</span><Status value={a.active?'active':'paused'}/><span>{a.interactions} recorded interactions · 30 days</span></summary><label>NFC URL<input readOnly value={`https://go.streetvouch.com/t/${a.token}?channel=nfc`}/></label><label>QR destination<input readOnly value={`https://go.streetvouch.com/t/${a.token}?channel=qr`}/></label><p>Encode the NFC tag and create the printed QR using these destinations. Inspect the real tag and scan before confirming tests.</p><button disabled={busy} onClick={()=>{if(confirm(`${a.active?'Disable':'Enable'} this customer entry point?`))act({action:'asset',businessId:b.id,id:a.id,active:!a.active,confirmed:true});}}>{a.active?'Disable':'Enable'} asset</button></details>)}{!p.assets.length&&<Empty title="No physical assets" text="Create a labelled asset for each customer feedback point."/>}</section><details className="op-panel op-pad"><summary>Create NFC / QR asset</summary><form onSubmit={e=>form(e,'/api/admin/assets')}><label>Label<input name="label" required/></label><label>Placement<input name="placement" required/></label><label>Type<select name="assetType">{['counter','barber_station','window','card','other'].map(x=><option key={x}>{x}</option>)}</select></label><button disabled={busy}>Create asset</button></form>{result?.nfcUrl&&<p>Created. Find the destinations in the asset list above.</p>}</details></>}
 {tab==='access'&&<><section className="op-panel"><div className="op-section-head"><h2>Owner accounts</h2><a href={`/api/admin/export?business=${encodeURIComponent(b.id)}`}>Export private feedback</a></div>{p.owners.map((o:Row)=><div className="op-health-row" key={o.id}><div><b>{o.display_name??o.email}</b><p>{o.email} · {o.role}</p><small>Last sign-in {date(o.last_login_at)}</small></div><Status value={o.active?'active':'invited'}/></div>)}{!p.owners.length&&<Empty title="No owner account" text="Create a secure invitation for the business owner."/>}</section><section className="op-panel op-pad"><h2>Invite an owner</h2><p>Creates a secure invitation link for you to share. Existing active accounts are kept active.</p><form onSubmit={e=>form(e,'/api/admin/invitations')}><label>Email<input name="email" type="email" defaultValue={b.contact_email??''} required/></label><label>Name<input name="displayName"/></label><button disabled={busy}>Create invitation link</button></form>{result?.invitationUrl&&<label>Secure invitation — expires {date(result.expiresAt)}<input readOnly value={result.invitationUrl}/></label>}</section></>}
 {tab==='activity'&&<section className="op-panel"><ActivityList rows={p.activity}/><p className="op-footnote">Latest 100 recorded actions.</p></section>}
 {tab==='analysis'&&<section className="op-panel"><div className="op-section-head"><h2>Recorded customer analysis</h2><span>Interpretations require review</span></div>{p.analysis.map((a:Row,i:number)=><article className="op-review" key={i}><p className="op-eyebrow">{a.model==='streetvouch-rules-v1'?'RULE-BASED SUGGESTION':'AI INTERPRETATION'} · {date(a.created_at)}</p><h3>{label(a.sentiment)} · {label(a.urgency)}</h3><p>{a.themes}</p><p><b>Suggested action:</b> {a.recommended_action}</p><details><summary>Why this was suggested</summary><p>{a.rationale}</p></details></article>)}{!p.analysis.length&&<Empty title="No saved analysis yet" text="Customer themes will appear when analysis has been recorded. No conclusions are inferred from an empty inbox."/>}<p className="op-footnote">These are interpretations of individual responses, not a survey of all customers or confirmed business outcomes.</p></section>}
 {tab==='performance'&&<section className="op-panel op-pad"><h2>Recorded activity</h2><p>Last 7 days compared with the preceding 7 days. Counts show observed activity; they do not establish cause or revenue impact.</p><div className="op-table-wrap"><table><thead><tr><th>Activity</th><th>Last 7 days</th><th>Previous 7 days</th></tr></thead><tbody>{['page_view','nfc_tap','qr_scan','google_click','private_submission','contact_request'].map(k=><tr key={k}><td>{label(k)}</td><td>{p.performance.find((r:Row)=>r.event_type===k&&r.period==='current')?.count??0}</td><td>{p.performance.find((r:Row)=>r.event_type===k&&r.period==='previous')?.count??0}</td></tr>)}</tbody></table></div><p className="op-muted">Low activity may reflect placement, trading hours or tracking coverage. Confirm with the owner before treating it as declining business performance.</p></section>}
 </>;
}
