import { env } from "cloudflare:workers";
import { allow, anonymousKey, BUSINESS, db, ensureBusiness, json, sameOrigin } from "../../_shared";
import { hashToken } from "../../../manager-auth";

export async function POST(request:Request){
  try{
    if(!sameOrigin(request))return json({ok:false},403);const body=await request.json() as {email?:string;website?:string};if(body.website)return json({ok:true,message:"If that email is authorised, a password link is on its way."});
    const email=body.email?.trim().toLowerCase();if(!email||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json({ok:false,message:"Enter a valid email address."},400);
    const database=db();await ensureBusiness(database);const rateKey=`manager-password-email:${await anonymousKey(request,"manager-password-email")}`;if(!await allow(database,rateKey,5,3600))return json({ok:false,message:"Too many requests. Please try again later."},429);const allowed=(env.OWNER_EMAIL??"").toLowerCase();if(email!==allowed)return json({ok:true,message:"If that email is authorised, a password link is on its way."});
    const now=new Date(),existing=await database.prepare("SELECT id FROM manager_users WHERE business_id=? AND email=?").bind(BUSINESS.id,email).first<{id:string}>(),managerId=existing?.id??crypto.randomUUID();await database.prepare("INSERT INTO manager_users (id,business_id,email,display_name,role,active,created_at) VALUES (?,?,?,?, 'owner',1,?) ON CONFLICT(business_id,email) DO UPDATE SET active=1").bind(managerId,BUSINESS.id,email,"Village Barbers manager",now.toISOString()).run();
    const token=crypto.randomUUID()+crypto.randomUUID().replaceAll("-","");const hash=await hashToken(token),expires=new Date(now.getTime()+15*60*1000).toISOString();await database.prepare("INSERT INTO manager_login_tokens (token_hash,manager_user_id,purpose,expires_at,created_at) VALUES (?,?,'reset',?,?)").bind(hash,managerId,expires,now.toISOString()).run();
    if(!env.RESEND_API_KEY)return json({ok:false,message:"Email delivery is temporarily unavailable."},503);const origin=new URL(request.url).origin,link=`${origin}/api/manager/verify?token=${encodeURIComponent(token)}`;
    const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from:env.EMAIL_FROM??"StreetVouch <onboarding@resend.dev>",to:[email],subject:"Reset your StreetVouch password",html:`<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto;padding:32px;color:#142829"><div style="font-weight:800;font-size:20px;margin-bottom:28px">✓ streetvouch</div><h1 style="font-family:Georgia,serif;font-size:34px">Reset your dashboard password</h1><p>Use this link to choose a new Village Barbers manager password. It expires in 15 minutes.</p><p style="margin:28px 0"><a href="${link}" style="background:#142829;color:#fff;text-decoration:none;padding:14px 20px;border-radius:10px;font-weight:700">Reset password</a></p><p style="color:#617170;font-size:13px">If you didn’t request this, you can ignore this email.</p></div>`})});if(!response.ok)throw new Error(`Email service returned ${response.status}`);return json({ok:true,message:"Check your email for the password reset link."});
  }catch(error){console.error("manager_magic_link_failed",error);return json({ok:false,message:"We couldn’t send the sign-in link. Please try again."},503);}
}
