import { env } from "cloudflare:workers";
import { headers } from "next/headers";
import { adminAllowed, BUSINESS, db, json, sameOrigin } from "../../_shared";
export async function POST(request:Request){
  const h=await headers();if(!adminAllowed(h)||!sameOrigin(request))return json({ok:false,message:"Access denied."},403);
  if(!env.RESEND_API_KEY||!env.OWNER_EMAIL)return json({ok:false,message:"Add the barber’s email and email-service key before sending reports."},409);
  const database=db(),since=new Date(Date.now()-7*86400000).toISOString();
  const [events,feedback,business]=await Promise.all([database.prepare("SELECT event_type,COUNT(*) count FROM events WHERE business_id=? AND created_at>=? GROUP BY event_type").bind(BUSINESS.id,since).all<{event_type:string;count:number}>(),database.prepare("SELECT status,severity,contact_requested,message FROM feedback WHERE business_id=? AND created_at>=? ORDER BY created_at DESC").bind(BUSINESS.id,since).all<{status:string;severity:string;contact_requested:number;message:string}>(),database.prepare("SELECT baseline_google_reviews,current_google_reviews FROM businesses WHERE id=?").bind(BUSINESS.id).first<{baseline_google_reviews:number;current_google_reviews:number}>()]);
  const counts=Object.fromEntries(events.results.map(r=>[r.event_type,r.count])),items=feedback.results,flagged=items.filter(x=>x.severity!=="normal"),waiting=items.filter(x=>x.contact_requested&&x.status!=="resolved"),gain=(business?.current_google_reviews??7)-(business?.baseline_google_reviews??7);
  const text=`Village Barbers Cobham — weekly StreetVouch summary\n\nPage visits: ${counts.page_view??0}\nGoogle-review clicks: ${counts.google_click??0}\nPrivate feedback: ${counts.private_submission??0}\nContact requests: ${counts.contact_request??0}\nNew Google reviews: ${gain}\n\n${flagged.length} feedback item(s) flagged for attention.\n${waiting.length} customer(s) awaiting contact.\n\nRecent customer themes:\n${items.slice(0,5).map(x=>`• ${x.message}`).join("\n")||"No private feedback received this week."}\n\nManage feedback: https://go.streetvouch.com/admin`;
  try{const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from:env.EMAIL_FROM??"StreetVouch <reports@streetvouch.com>",to:[env.OWNER_EMAIL],subject:"Your Village Barbers customer pulse",text})});if(!response.ok)throw new Error(`Email service returned ${response.status}`);return json({ok:true,message:"Weekly summary sent."});}
  catch(error){console.error("weekly_summary_failed",error);return json({ok:false,message:"The report could not be sent. Please try again."},503);}
}
