import { env } from "cloudflare:workers";
import { classifyComment } from "../lib/weekly-report";
import { classifyFeedbackSeverity } from "../lib/security";

export type Analysis={urgency:"routine"|"attention"|"urgent"|"critical";confidence:number;sentiment:"positive"|"mixed"|"negative"|"neutral";themes:string[];recommended_action:string;draft_reply:string;rationale:string;model:string};

const themeMap:Array<[RegExp,string]>=[[/\b(wait|queue|late|delay)\b/i,"waiting time"],[/\b(friendly|welcome|staff|service)\b/i,"service"],[/\b(cut|hair|trim|fade|beard)\b/i,"cut quality"],[/\b(clean|hygiene|dirty)\b/i,"cleanliness"],[/\b(price|cost|value|expensive)\b/i,"value"]];

export function fallbackAnalysis(text:string,rating?:number):Analysis{
  const severity=classifyFeedbackSeverity(text),lower=text.toLowerCase(),mild=/\bnot bad\b/i.test(text),positive=!mild&&(/\b(good|great|excellent|amazing|friendly|nice|love|lovely|perfect|best|incredible|happy|recommend|okay|ok)\b/i.test(text)||(rating!==undefined&&rating>=4)),negative=!mild&&(/\b(bad|poor|rude|awful|terrible|worst|hate|disappoint|unhappy|refund|complaint)\b/i.test(text)||/\b(won't|wouldn't|will not|not)\s+(be\s+)?(returning|return|come back|coming back)\b/i.test(text)||/\bnever\s+(again|return|coming back)\b/i.test(text)||(rating!==undefined&&rating<=3));
  const urgency=severity==="serious"?"urgent":severity==="attention"?"attention":"routine",sentiment=classifyComment(text,rating).sentiment,themes=themeMap.filter(([pattern])=>pattern.test(lower)).map(([,theme])=>theme);
  return{urgency,confidence:severity==="normal"?60:90,sentiment,themes:themes.length?themes:["general experience"],recommended_action:urgency==="urgent"?"Review immediately and contact the customer where possible.":urgency==="attention"?"Review today and decide whether follow-up is needed.":"Review during the normal feedback workflow.",draft_reply:sentiment==="positive"?"Thank you for your kind feedback. We really appreciate it and hope to see you again soon.":"Thank you for sharing this. We’re sorry your experience did not meet expectations. We’d like to understand what happened and put it right.",rationale:"Rule-based safety analysis used while AI processing is unavailable.",model:"streetvouch-rules-v1"};
}

export async function analyseCustomerText(text:string,sourceType:"feedback"|"google_review",rating?:number):Promise<Analysis>{
  if(!env.OPENAI_API_KEY)return fallbackAnalysis(text,rating);
  const model=env.OPENAI_MODEL??"gpt-5.5";
  const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model,store:false,max_output_tokens:700,instructions:"You analyse genuine customer feedback for a local business. Classify operational urgency, extract concise themes, recommend a safe next action, and draft a warm concise reply in the business voice. Never promise refunds, compensation, legal outcomes, medical advice, or that an issue is resolved. Critical means an immediate credible threat to life or safety. Urgent includes injury, discrimination, harassment, infection, safeguarding, threats or legal escalation. Attention means a service problem needing same-day review. Routine covers praise and ordinary suggestions. A human manager must approve every reply.",input:`Source: ${sourceType}\nStar rating: ${rating??"not supplied"}\nCustomer text:\n${text.slice(0,4000)}`,text:{format:{type:"json_schema",name:"streetvouch_feedback_analysis",strict:true,schema:{type:"object",additionalProperties:false,properties:{urgency:{type:"string",enum:["routine","attention","urgent","critical"]},confidence:{type:"integer",minimum:0,maximum:100},sentiment:{type:"string",enum:["positive","mixed","negative","neutral"]},themes:{type:"array",items:{type:"string"},maxItems:6},recommended_action:{type:"string"},draft_reply:{type:"string"},rationale:{type:"string"}},required:["urgency","confidence","sentiment","themes","recommended_action","draft_reply","rationale"]}}}})});
  if(!response.ok)throw new Error(`OpenAI analysis returned ${response.status}`);
  const data=await response.json() as {output_text?:string;output?:Array<{content?:Array<{type:string;text?:string}>}>};data.output_text??=data.output?.flatMap(item=>item.content??[]).filter(item=>item.type==="output_text").map(item=>item.text??"").join("");if(!data.output_text)throw new Error("OpenAI analysis returned no structured output");
  const parsed=JSON.parse(data.output_text) as Omit<Analysis,"model">;return{...parsed,model};
}
