import { env } from "cloudflare:workers";
import { db } from "./api/_shared";

const encoder=new TextEncoder(),decoder=new TextDecoder();
const b64=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes));
const unb64=(value:string)=>Uint8Array.from(atob(value),char=>char.charCodeAt(0));
async function encryptionKey(){if(!env.GOOGLE_TOKEN_ENCRYPTION_KEY)throw new Error("Google token encryption is not configured");const digest=await crypto.subtle.digest("SHA-256",encoder.encode(env.GOOGLE_TOKEN_ENCRYPTION_KEY));return crypto.subtle.importKey("raw",digest,"AES-GCM",false,["encrypt","decrypt"]);}
export async function encryptToken(value:string){const iv=crypto.getRandomValues(new Uint8Array(12)),encrypted=await crypto.subtle.encrypt({name:"AES-GCM",iv},await encryptionKey(),encoder.encode(value));return{encrypted:b64(new Uint8Array(encrypted)),iv:b64(iv)};}
export async function decryptToken(value:string,iv:string){const decrypted=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(iv)},await encryptionKey(),unb64(value));return decoder.decode(decrypted);}
export async function googleAccessToken(refreshToken:string){const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID??"",client_secret:env.GOOGLE_CLIENT_SECRET??"",refresh_token:refreshToken,grant_type:"refresh_token"})});if(!response.ok)throw new Error(`Google token refresh failed (${response.status})`);const data=await response.json() as {access_token?:string};if(!data.access_token)throw new Error("Google did not return an access token");return data.access_token;}
async function googleJson<T>(url:string,accessToken:string){const response=await fetch(url,{headers:{Authorization:`Bearer ${accessToken}`}});if(!response.ok)throw new Error(`Google API returned ${response.status}`);return response.json() as Promise<T>;}
export type GoogleLocation={accountName:string;locationName:string;title:string};
export async function listGoogleLocations(accessToken:string){const accounts=await googleJson<{accounts?:Array<{name:string}>}>("https://mybusinessaccountmanagement.googleapis.com/v1/accounts",accessToken),result:GoogleLocation[]=[];for(const account of accounts.accounts??[]){const locations=await googleJson<{locations?:Array<{name:string;title?:string}>}>(`https://mybusinessbusinessinformation.googleapis.com/v1/${account.name}/locations?readMask=name,title&pageSize=100`,accessToken);for(const location of locations.locations??[])result.push({accountName:account.name,locationName:location.name,title:location.title??"Google Business Profile"});}return result;}
export async function findFirstLocation(accessToken:string){const locations=await listGoogleLocations(accessToken);if(locations[0])return locations[0];throw new Error("No managed Google Business Profile location was found");}
const ratingNumber=(rating:string|number)=>typeof rating==="number"?rating:({ONE:1,TWO:2,THREE:3,FOUR:4,FIVE:5} as Record<string,number>)[rating]??0;
export async function syncGoogleReviews(businessId:string){const database=db(),connection=await database.prepare("SELECT encrypted_refresh_token,token_iv,google_account_name,google_location_name FROM google_connections WHERE business_id=? AND status IN ('connected','sync_failed')").bind(businessId).first<{encrypted_refresh_token:string;token_iv:string;google_account_name:string;google_location_name:string}>();if(!connection?.encrypted_refresh_token||!connection.token_iv||!connection.google_account_name||!connection.google_location_name)throw new Error("Google Business Profile is not connected");const accessToken=await googleAccessToken(await decryptToken(connection.encrypted_refresh_token,connection.token_iv)),accountId=connection.google_account_name.split("/").pop(),locationId=connection.google_location_name.split("/").pop();let pageToken="",synced=0;do{const url=new URL(`https://mybusiness.googleapis.com/v4/accounts/${accountId}/locations/${locationId}/reviews`);url.searchParams.set("pageSize","50");url.searchParams.set("orderBy","updateTime desc");if(pageToken)url.searchParams.set("pageToken",pageToken);const data=await googleJson<{reviews?:Array<{name:string;reviewId?:string;reviewer?:{displayName?:string};starRating:string|number;comment?:string;createTime:string;updateTime:string;reviewReply?:{comment?:string}}>;nextPageToken?:string}>(url.toString(),accessToken),now=new Date().toISOString();for(const review of data.reviews??[]){const googleId=review.reviewId??review.name.split("/").pop()??review.name,rating=ratingNumber(review.starRating);await database.prepare(`INSERT INTO google_reviews (id,business_id,google_review_id,reviewer_name,rating,comment,google_created_at,google_updated_at,reply_comment,reply_status,synced_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(business_id,google_review_id) DO UPDATE SET reviewer_name=excluded.reviewer_name,rating=excluded.rating,comment=excluded.comment,google_created_at=excluded.google_created_at,google_updated_at=excluded.google_updated_at,reply_comment=excluded.reply_comment,reply_status=excluded.reply_status,synced_at=excluded.synced_at`).bind(crypto.randomUUID(),businessId,googleId,review.reviewer?.displayName??null,rating,review.comment??null,review.createTime,review.updateTime,review.reviewReply?.comment??null,review.reviewReply?.comment?"published":"none",now).run();synced++;}pageToken=data.nextPageToken??"";}while(pageToken);await database.prepare("UPDATE google_connections SET status='connected',last_synced_at=?,last_error=NULL,updated_at=? WHERE business_id=?").bind(new Date().toISOString(),new Date().toISOString(),businessId).run();return synced;}

export async function publishGoogleReply(businessId:string,reviewId:string,comment:string){
  const database=db();
  const [connection,review]=await Promise.all([
    database.prepare("SELECT encrypted_refresh_token,token_iv,google_account_name,google_location_name FROM google_connections WHERE business_id=? AND status='connected'").bind(businessId).first<{encrypted_refresh_token:string;token_iv:string;google_account_name:string;google_location_name:string}>(),
    database.prepare("SELECT google_review_id FROM google_reviews WHERE id=? AND business_id=?").bind(reviewId,businessId).first<{google_review_id:string}>()
  ]);
  if(!connection?.encrypted_refresh_token||!connection.token_iv||!connection.google_account_name||!connection.google_location_name||!review)throw new Error("Google review connection is unavailable");
  const accessToken=await googleAccessToken(await decryptToken(connection.encrypted_refresh_token,connection.token_iv));
  const accountId=connection.google_account_name.split("/").pop(),locationId=connection.google_location_name.split("/").pop();
  const response=await fetch(`https://mybusiness.googleapis.com/v4/accounts/${accountId}/locations/${locationId}/reviews/${review.google_review_id}/reply`,{method:"PUT",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({comment})});
  if(!response.ok)throw new Error(`Google reply failed (${response.status})`);
  await database.prepare("UPDATE google_reviews SET reply_comment=?,reply_status='published' WHERE id=? AND business_id=?").bind(comment,reviewId,businessId).run();
}
