import { db } from "./api/_shared";
import { decryptToken, googleAccessToken } from "./google";
type Connection={encrypted_refresh_token:string|null;token_iv:string|null;search_property:string|null;analytics_property:string|null};
const iso=(time:number)=>new Date(time).toISOString().slice(0,10);
async function googleRequest<T>(url:string,token:string,body?:unknown):Promise<T>{const response=await fetch(url,{method:body===undefined?"GET":"POST",headers:{Authorization:`Bearer ${token}`,...(body===undefined?{}:{"Content-Type":"application/json"})},body:body===undefined?undefined:JSON.stringify(body)});if(!response.ok)throw new Error(`Google API ${response.status}: ${(await response.text()).slice(0,150)}`);return response.json() as Promise<T>;}
export async function visibilityToken(businessId:string){const row=await db().prepare("SELECT encrypted_refresh_token,token_iv,search_property,analytics_property FROM visibility_connections WHERE business_id=?").bind(businessId).first<Connection>();if(!row?.encrypted_refresh_token||!row.token_iv)throw new Error("Visibility account not connected");return {token:await googleAccessToken(await decryptToken(row.encrypted_refresh_token,row.token_iv)),connection:row};}
export async function searchProperties(token:string){const response=await googleRequest<{siteEntry?:Array<{siteUrl:string;permissionLevel:string}>}>("https://www.googleapis.com/webmasters/v3/sites",token);return (response.siteEntry??[]).filter(p=>p.permissionLevel!=="siteUnverifiedUser").map(p=>p.siteUrl);}
export async function analyticsProperties(token:string){let next="",out:Array<{name:string;label:string}>=[];do{const url=new URL("https://analyticsadmin.googleapis.com/v1beta/accountSummaries");url.searchParams.set("pageSize","200");if(next)url.searchParams.set("pageToken",next);const data=await googleRequest<{accountSummaries?:Array<{propertySummaries?:Array<{property:string;displayName?:string}>}>;nextPageToken?:string}>(url.toString(),token);out=out.concat((data.accountSummaries??[]).flatMap(a=>(a.propertySummaries??[]).map(p=>({name:p.property,label:p.displayName??p.property}))));next=data.nextPageToken??"";}while(next);return out;}
export async function collectVisibility(businessId:string){const database=db(),{token,connection}=await visibilityToken(businessId),now=new Date().toISOString(),end=iso(Date.now()-3*86400000),start=iso(Date.now()-190*86400000);
  if(!connection.search_property)throw new Error("Select a verified Search Console property");
  const property=encodeURIComponent(connection.search_property),api=`https://www.googleapis.com/webmasters/v3/sites/${property}/searchAnalytics/query`;
  const dates=await googleRequest<{rows?:Array<{keys:string[];clicks:number;impressions:number;position:number}>}>(api,token,{startDate:start,endDate:end,dimensions:["date"],rowLimit:1000,dataState:"final"});
  for(const row of dates.rows??[])await database.prepare(`INSERT INTO visibility_daily (business_id,date,search_clicks,search_impressions,search_position_sum,collected_at) VALUES (?,?,?,?,?,?) ON CONFLICT(business_id,date) DO UPDATE SET search_clicks=excluded.search_clicks,search_impressions=excluded.search_impressions,search_position_sum=excluded.search_position_sum,collected_at=excluded.collected_at`).bind(businessId,row.keys[0],Math.round(row.clicks),Math.round(row.impressions),Math.round(row.position*row.impressions*100),now).run();
  const observed=new Set((dates.rows??[]).map(r=>r.keys[0]));for(let time=Date.parse(`${start}T00:00:00Z`);time<=Date.parse(`${end}T00:00:00Z`);time+=86400000){const date=iso(time);if(!observed.has(date))await database.prepare("INSERT INTO visibility_daily (business_id,date,search_clicks,search_impressions,search_position_sum,collected_at) VALUES (?,?,0,0,NULL,?) ON CONFLICT(business_id,date) DO UPDATE SET search_clicks=0,search_impressions=0,search_position_sum=NULL,collected_at=excluded.collected_at").bind(businessId,date,now).run();}
  for(const kind of ["query","page"]){for(let offset=0;offset<50000;offset+=25000){const data=await googleRequest<{rows?:Array<{keys:string[];clicks:number;impressions:number;position:number}>}>(api,token,{startDate:start,endDate:end,dimensions:["date",kind],rowLimit:25000,startRow:offset,dataState:"final"});for(const row of data.rows??[])await database.prepare(`INSERT INTO visibility_search_rows (business_id,date,kind,value,clicks,impressions,position) VALUES (?,?,?,?,?,?,?) ON CONFLICT(business_id,date,kind,value) DO UPDATE SET clicks=excluded.clicks,impressions=excluded.impressions,position=excluded.position`).bind(businessId,row.keys[0],kind,row.keys[1],Math.round(row.clicks),Math.round(row.impressions),Math.round(row.position*100)).run();if((data.rows?.length??0)<25000)break;}}
  let analyticsError:string|null=null;
  if(connection.analytics_property){try{const data=await googleRequest<{rows?:Array<{dimensionValues:Array<{value:string}>;metricValues:Array<{value:string}>}>}>(`https://analyticsdata.googleapis.com/v1beta/${connection.analytics_property}:runReport`,token,{dateRanges:[{startDate:start,endDate:end}],dimensions:[{name:"date"},{name:"sessionDefaultChannelGroup"},{name:"sessionSource"}],metrics:[{name:"sessions"}],limit:100000});const counts=new Map<string,{organic:number;ai:number}>();for(const row of data.rows??[]){const day=row.dimensionValues[0].value.replace(/^(\d{4})(\d{2})(\d{2})$/,"$1-$2-$3"),v=counts.get(day)??{organic:0,ai:0},n=Number(row.metricValues[0].value),channel=row.dimensionValues[1].value,source=row.dimensionValues[2].value.toLowerCase();if(channel==="Organic Search")v.organic+=n;if(/chatgpt|perplexity|copilot|gemini\.google/.test(source))v.ai+=n;counts.set(day,v);}for(let time=Date.parse(`${start}T00:00:00Z`);time<=Date.parse(`${end}T00:00:00Z`);time+=86400000){const day=iso(time),v=counts.get(day)??{organic:0,ai:0};await database.prepare("UPDATE visibility_daily SET analytics_organic_sessions=?,ai_referral_sessions=? WHERE business_id=? AND date=?").bind(v.organic,v.ai,businessId,day).run();}}catch(e){analyticsError=String(e).slice(0,180);}}
  await database.prepare("UPDATE visibility_connections SET status=?,last_error=?,last_collected_at=?,updated_at=? WHERE business_id=?").bind(analyticsError?"partial":"connected",analyticsError,now,now,businessId).run();await checkBusinessWebsite(businessId,connection.search_property,token).catch(e=>console.error("visibility_website_check_failed",e));return {searchDays:dates.rows?.length??0,analyticsError};
}
async function checkBusinessWebsite(businessId:string,property:string,token:string){const database=db(),business=await database.prepare("SELECT website FROM businesses WHERE id=?").bind(businessId).first<{website:string|null}>();if(!business?.website)return;const url=new URL(business.website);if(url.protocol!=="https:"||url.username||url.password||url.port||!/^[a-z0-9.-]+$/i.test(url.hostname)||!url.hostname.includes(".")||/(^|\.)(localhost|local|internal)$/.test(url.hostname)||/^\d+\.\d+\.\d+\.\d+$/.test(url.hostname))return;const root=new URL(property.startsWith("sc-domain:")?`https://${property.slice(10)}`:property);if(url.hostname!==root.hostname&&url.hostname!==`www.${root.hostname}`&&root.hostname!==`www.${url.hostname}`)return;const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(url.toString(),{redirect:"manual",signal:controller.signal,headers:{"User-Agent":"StreetVouchVisibility/1.0"}}),html=(await response.text()).slice(0,500000),title=html.match(/<title[^>]*>([^<]*)<\/title>/i)?.[1]?.trim()??null,robots=html.match(/<meta[^>]+name=["']robots["'][^>]+content=["']([^"']+)/i)?.[1]??"",noindex=/\bnoindex\b/i.test(robots)||/\bnoindex\b/i.test(response.headers.get("x-robots-tag")??""),localBusiness=/"@type"\s*:\s*"(?:LocalBusiness|BarberShop|HairSalon|BeautySalon)"/i.test(html),issues=[response.status>=400?`Page returned ${response.status}`:null,response.status>=300&&response.status<400?"Page redirects; confirm this is intentional":null,noindex?"Page asks search engines not to index it":null,!title?"Page title is missing":null,!localBusiness?"LocalBusiness details were not detected in page markup":null].filter(Boolean);
 const robotsResponse=await fetch(new URL("/robots.txt",url.origin),{signal:controller.signal,redirect:"manual"}),robotsText=robotsResponse.ok?(await robotsResponse.text()).slice(0,100000):"";let group="",blocks=false;for(const raw of robotsText.split(/\r?\n/)){const line=raw.split("#")[0].trim();if(/^user-agent:/i.test(line))group=line.slice(line.indexOf(":")+1).trim().toLowerCase();else if(/^disallow:\s*\/\s*$/i.test(line)&&["*","googlebot"].includes(group))blocks=true;}if(blocks)issues.push("robots.txt may block Google; review crawler rules");const sitemapResponse=await fetch(new URL("/sitemap.xml",url.origin),{signal:controller.signal,redirect:"manual"});if(sitemapResponse.status===404&&!/sitemap:/i.test(robotsText))issues.push("No sitemap found at /sitemap.xml or declared in robots.txt");
 try{const inspected=await googleRequest<{inspectionResult?:{indexStatusResult?:{coverageState?:string;indexingState?:string}}}>("https://searchconsole.googleapis.com/v1/urlInspection/index:inspect",token,{inspectionUrl:url.toString(),siteUrl:property});const result=inspected.inspectionResult?.indexStatusResult;if(result?.indexingState&&result.indexingState!=="INDEXING_ALLOWED")issues.push(`Google URL Inspection: ${result.indexingState}`);}catch(error){console.error("visibility_url_inspection_unavailable",error);}
 await database.prepare(`INSERT INTO visibility_health (business_id,url,status,final_url,title,noindex,robots_blocked,local_business,issue,checked_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(business_id,url) DO UPDATE SET status=excluded.status,final_url=excluded.final_url,title=excluded.title,noindex=excluded.noindex,robots_blocked=excluded.robots_blocked,local_business=excluded.local_business,issue=excluded.issue,checked_at=excluded.checked_at`).bind(businessId,url.toString(),response.status,response.headers.get("location")??url.toString(),title,noindex?1:0,blocks?1:0,localBusiness?1:0,issues.join("; ")||null,new Date().toISOString()).run();}finally{clearTimeout(timeout);}}
