import { env } from "cloudflare:workers";
import Script from "next/script";
import Link from "next/link";
import { Bell, Settings, ArrowUpRight, MessageSquare, Star, ScanLine, Eye, MousePointerClick, Check, ChartColumnIncreasing } from "lucide-react";
import { classifyComment } from "../../lib/weekly-report";

type Session={businessId:string;businessSlug:string;businessName:string};
type Feedback={id:string;message:string;customer_name:string|null;customer_email:string|null;created_at:string;status:string;severity:string;contact_requested:number;contacted_at:string|null;internal_note:string|null;due_at:string|null};
type Review={id:string;comment:string|null;rating:number;reviewer_name:string|null;google_created_at:string;reply_status:string;reply_comment:string|null};
type Connection={status:string;last_synced_at:string|null};
const tones=["positive","mixed","neutral","negative"] as const;
const colours={positive:"#54a63f",mixed:"#e8ac35",neutral:"#91a2b8",negative:"#ed7064"};
const date=(v:string)=>new Date(v).toLocaleDateString("en-GB",{day:"numeric",month:"short",timeZone:"Europe/London"});
const day=86400000;
const delta=(a:number,b:number)=>a===b?"No change":`${a>b?"+":""}${a-b} vs previous period`;
const closed=(s:string)=>s==="resolved"||s==="archived";
export default async function Dashboard({session,query}:{session:Session;query:Record<string,string|undefined>}){
  if(!env.DB)throw new Error("Database unavailable");
  const now=Date.now(),days=[7,30,90].includes(Number(query.range))?Number(query.range):7;
  const end=new Date(now).toISOString(),since=new Date(now-days*day).toISOString(),previous=new Date(now-days*2*day).toISOString();
  const historyStart=new Date(Math.min(now-56*day,now-days*2*day)).toISOString();
  const id=session.businessId,base=`/manager/${session.businessSlug}`;
  const [f,r,e,c,reports,business]=await Promise.all([
    env.DB.prepare("SELECT * FROM feedback WHERE business_id=? AND (created_at>=? OR status NOT IN ('resolved','archived')) ORDER BY created_at DESC").bind(id,historyStart).all<Feedback>(),
    env.DB.prepare("SELECT * FROM google_reviews WHERE business_id=? ORDER BY google_created_at DESC").bind(id).all<Review>(),
    env.DB.prepare("SELECT event_type, CASE WHEN created_at>=? THEN 'current' ELSE 'previous' END period,COUNT(*) count FROM events WHERE business_id=? AND created_at>=? AND created_at<? GROUP BY event_type,period").bind(since,id,previous,end).all<{event_type:string;period:string;count:number}>(),
    env.DB.prepare("SELECT status,last_synced_at FROM google_connections WHERE business_id=?").bind(id).first<Connection>(),
    env.DB.prepare("SELECT status,created_at FROM report_deliveries WHERE business_id=? ORDER BY created_at DESC LIMIT 3").bind(id).all<{status:string;created_at:string}>(),
    env.DB.prepare("SELECT address,created_at FROM businesses WHERE id=?").bind(id).first<{address:string|null;created_at:string}>()
  ]);
  const connected=c?.status==="connected",available=Boolean(c?.last_synced_at),feedback=f.results,reviews=r.results;
  const view=query.source==="google"?"google":query.section==="inbox"?"inbox":query.section==="reports"?"reports":"overview";
  const viewTitle={overview:session.businessName,inbox:"Feedback inbox",google:"Google reviews",reports:"Weekly reports"}[view];
  const inPeriod=(d:string)=>d>=since&&d<end,prior=(d:string)=>d>=previous&&d<since;
  const pf=feedback.filter(x=>inPeriod(x.created_at)),pr=reviews.filter(x=>inPeriod(x.google_created_at));
  const previousF=feedback.filter(x=>prior(x.created_at)),previousR=reviews.filter(x=>prior(x.google_created_at));
  const classify=(x:Feedback)=>classifyComment(x.message,undefined,Boolean(x.contact_requested));
  const waiting=feedback.filter(x=>x.contact_requested&&!x.contacted_at&&!closed(x.status));
  const flagged=feedback.filter(x=>x.severity!=="normal"&&!closed(x.status));
  const pending=reviews.filter(x=>!x.reply_comment&&x.reply_status!=="published");
  const urgent=feedback.filter(x=>!closed(x.status)&&(waiting.includes(x)||flagged.includes(x)||classify(x).sentiment==="negative"||(x.due_at&&x.due_at<end)));
  const attention=urgent.length+pending.length;
  const comments=[...pf.filter(x=>x.message.trim()).map(x=>({key:x.id,text:x.message,source:"Private feedback",created:x.created_at,requested:Boolean(x.contact_requested&&!x.contacted_at&&!closed(x.status)),status:x.status,analysis:classify(x),href:`${base}?range=${days}&section=inbox#item-${x.id}`})),...pr.filter(x=>x.comment?.trim()).map(x=>({key:x.id,text:x.comment!,source:"Google review",created:x.google_created_at,requested:false,status:x.reply_comment?"Replied":"Reply needed",analysis:classifyComment(x.comment!,x.rating),href:`${base}?range=${days}&source=google#review-${x.id}`}))];
  const previousComments=[...previousF.map(classify),...previousR.filter(x=>x.comment?.trim()).map(x=>classifyComment(x.comment!,x.rating))];
  const sentiment=tones.map(t=>({tone:t,count:comments.filter(x=>x.analysis.sentiment===t).length}));
  const total=comments.length,raw=sentiment.map(x=>total?x.count/total*100:0),percent=raw.map(Math.floor);
  [...raw.keys()].sort((a,b)=>(raw[b]-percent[b])-(raw[a]-percent[a])).slice(0,total?100-percent.reduce((a,b)=>a+b,0):0).forEach(i=>percent[i]++);
  let acc=0;const gradient=sentiment.map(x=>{const start=acc;acc+=total?x.count/total*100:0;return `${colours[x.tone]} ${start}% ${acc}%`;}).join(",");
  const themeNames=[...new Set(comments.flatMap(x=>x.analysis.themes))];
  const themes=themeNames.map(name=>{const items=comments.filter(x=>x.analysis.themes.includes(name));const counts=tones.map(t=>({tone:t,count:items.filter(x=>x.analysis.sentiment===t).length})).sort((a,b)=>b.count-a.count);return {name,items,dominant:counts[0].count>(counts[1]?.count??0)?counts[0].tone:"mixed",previous:previousComments.filter(x=>x.themes.includes(name)).length};}).sort((a,b)=>b.items.length-a.items.length);
  const selected:typeof comments=[];for(const predicate of [(x:typeof comments[number])=>x.analysis.sentiment==="positive",(x:typeof comments[number])=>x.analysis.sentiment==="mixed",(x:typeof comments[number])=>x.analysis.sentiment==="negative",(x:typeof comments[number])=>x.requested]){const match=comments.find(x=>predicate(x)&&!selected.includes(x));if(match)selected.push(match);}
  if(selected.length<4)for(const x of comments){if(selected.length===4)break;if(!selected.includes(x))selected.push(x);}
  const metric=(type:string,period="current")=>e.results.find(x=>x.event_type===type&&x.period===period)?.count??0;
  const metrics=[{label:"NFC + QR interactions",value:metric("nfc_tap")+metric("qr_scan"),old:metric("nfc_tap","previous")+metric("qr_scan","previous"),icon:ScanLine,help:"Recorded taps and scans"},{label:"Customer page visits",value:metric("page_view"),old:metric("page_view","previous"),icon:Eye,help:"Visits, including repeat visits"},{label:"Google review opens",value:metric("google_click"),old:metric("google_click","previous"),icon:MousePointerClick,help:"Clicks through to Google"},{label:"Private feedback",value:pf.length,old:previousF.length,icon:MessageSquare,help:"Messages received"},{label:"New Google reviews",value:available?pr.length:null,old:previousR.length,icon:Star,help:available?"Confirmed, imported reviews":"Connect Google to measure"},{label:"New reviews’ rating",value:available&&pr.length?Number((pr.reduce((s,x)=>s+x.rating,0)/pr.length).toFixed(1)):null,old:null,icon:Star,help:"Average out of 5 in this period"}];
  const weekCount=Math.ceil(days/7),weeks=Array.from({length:weekCount},(_,i)=>{const start=now-Math.min(days,(weekCount-i)*7)*day,finish=now-Math.max(0,(weekCount-i-1)*7)*day;return {start,finish,label:date(new Date(start).toISOString()),private:feedback.filter(x=>Date.parse(x.created_at)>=start&&Date.parse(x.created_at)<finish).length,google:reviews.filter(x=>Date.parse(x.google_created_at)>=start&&Date.parse(x.google_created_at)<finish).length};}).filter(w=>!business||w.finish>Date.parse(business.created_at));
  const max=Math.max(1,...weeks.flatMap(w=>[w.private,w.google])),peak=Math.ceil(max/4)*4;
  const googleMessage=connected?"Google connected":available?"Google needs attention":"Google not connected";
  return <><link rel="stylesheet" href="/manager-dashboard.css"/><main className={`sv-dashboard view-${view}`}>
    <header className="sv-header"><Link className="sv-brand" href={base}><span>✓</span>streetvouch</Link><nav aria-label="Manager navigation"><Link href={`${base}?range=${days}#overview`} aria-current={!query.section&&!query.source?"page":undefined}>Overview</Link><Link href={`${base}?range=${days}&section=inbox#inbox`} aria-current={query.section==="inbox"?"page":undefined}>Inbox</Link><Link href={`${base}?range=${days}&source=google#inbox`} aria-current={query.source==="google"?"page":undefined}>Google reviews</Link><Link href={`${base}/visibility`}>Visibility</Link><Link href={`${base}?range=${days}&section=reports#report`} aria-current={query.section==="reports"?"page":undefined}>Reports</Link></nav><div className="sv-header-tools"><Link href={`${base}?range=${days}&section=inbox&view=attention#inbox`} aria-label={`${attention} ${attention===1?"item needs":"items need"} attention`} className="sv-icon"><Bell size={20}/><span>{attention}</span></Link><Link href={`${base}/onboarding`} className="sv-icon" aria-label="Business settings"><Settings size={20}/></Link><form action="/api/manager/logout" method="post"><button className="sv-text">Sign out</button></form></div></header>
    <div className="sv-workspace" id="overview">{query.from==="admin"&&<a href="/admin">← StreetVouch admin</a>}
      <div className="sv-page-heading"><div><p className="sv-eyebrow">{view==="overview"?"YOUR CUSTOMER PULSE":session.businessName}</p><h1>{viewTitle}</h1>{view==="overview"&&business?.address&&<p className="sv-muted">{business.address}</p>}{(view==="overview"||view==="google")&&<a className={`sv-connection ${connected?"is-connected":""}`} href={`${base}?range=${days}&source=google#google`}>{googleMessage} · {c?.last_synced_at?`Last synced ${date(c.last_synced_at)}`:"No reviews synced yet"}</a>}</div><form className="sv-range">{query.view&&<input type="hidden" name="view" value={query.view}/>}{query.theme&&<input type="hidden" name="theme" value={query.theme}/ >}{view==="inbox"&&<input type="hidden" name="section" value="inbox"/>}{view==="google"&&<input type="hidden" name="source" value="google"/>}{view==="reports"&&<input type="hidden" name="section" value="reports"/>}<label htmlFor="range">Reporting period</label><div><select name="range" id="range" defaultValue={days}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select><button className="sv-button secondary">Apply</button></div><small>{date(since)} – {date(end)}</small></form></div>
      <p id="manager-status" role="status" className="sv-status">{query.google==="setup_required"?"Google connection is not available yet. StreetVouch is completing the integration setup.":""}</p>
      <span id="sv-business-context" hidden data-name={session.businessName} data-address={business?.address??""} data-google-message={googleMessage} data-google-synced={c?.last_synced_at?`Last synced ${date(c.last_synced_at)}`:"No reviews synced yet"} data-google-connected={connected?"yes":"no"} data-google-available={available?"yes":"no"}/>
      <section className="sv-priority" data-view-section="overview"><div><span className="sv-eyebrow">YOUR NEXT MOVE</span><h2>{attention?`${attention} ${attention===1?"item needs":"items need"} your attention.`:"You’re all caught up."}</h2><p>{attention?"A little follow-up can make a big difference.":"No priority items outstanding. Take a moment to see what customers enjoyed."}</p><a className="sv-button lime" href={attention?`${base}?range=${days}&section=inbox&view=attention#inbox`:"#voice"}>{attention?"Review priority feedback":"Read customer highlights"}<ArrowUpRight size={18}/></a></div><div className="sv-priority-stats"><div><b>{pf.length}</b><span>Private messages</span></div><div><b>{available?pr.length:"—"}</b><span>Google reviews</span></div><div><b>{waiting.length}</b><span>Awaiting contact</span></div><div><b>{flagged.length}</b><span>Flagged & unresolved</span></div></div></section>
      <section aria-label="Period metrics" className="sv-metrics" data-view-section="overview">{metrics.map(({label,value,old,icon:Icon,help})=><article className="sv-metric" key={label}><div><Icon size={19}/><span>{label}</span></div><b>{value??"—"}</b><p>{help}</p><small>{value!==null&&old!==null?(business&&Date.parse(business.created_at)>Date.parse(previous)?"Building comparison history":delta(value,old)):""}</small></article>)}</section>
      <div className="sv-analysis-grid" data-view-section="overview"><section className="sv-card"><div className="sv-section-title"><div><p className="sv-eyebrow">ACTIVITY OVER TIME</p><h2>A week-by-week view</h2></div><ChartColumnIncreasing size={23}/></div><p className="sv-muted">Written feedback received · weekly periods in the selected range</p><div className="sv-legend"><span><i style={{background:"#8383eb"}}/>Private feedback</span><span><i style={{background:"#26a59b"}}/>Google reviews{!available&&" · not connected"}</span></div><div className="sv-chart" role="img" aria-label={weeks.map(w=>`${w.label}: ${w.private} private messages, ${available?w.google:"unavailable"} Google reviews`).join("; ")}><div className="sv-axis"><span>{peak}</span><span>{peak/2}</span><span>0</span></div><div className="sv-plot">{weeks.map(w=><div className="sv-week" key={w.start}><div className="sv-bars"><div className="sv-bar private" style={{height:`${w.private/peak*100}%`}}><span>{w.private}</span></div><div className="sv-bar google" style={{height:`${w.google/peak*100}%`}}><span>{available?w.google:"—"}</span></div></div><span className="sv-week-label">{w.label}</span></div>)}</div></div><p className="sv-footnote">Week starting dates. Google opens are not confirmed reviews. {weeks.length<2?"Choose 30 or 90 days to compare weeks.":""}</p></section>
      <section className="sv-card"><p className="sv-eyebrow">FEEDBACK SIGNALS</p><h2>How customers felt</h2><p className="sv-muted">{total} written {total===1?"response":"responses"} analysed</p><div className="sv-sentiment"><div className="sv-donut" role="img" aria-label={sentiment.map((s,i)=>`${s.tone}: ${s.count} (${percent[i]}%)`).join(", ")} style={{background:total?`conic-gradient(${gradient})`:"#e8edf0"}}><div><b>{total}</b><span>comments</span></div></div><div className="sv-sentiment-key">{sentiment.map((s,i)=><div key={s.tone}><span><i style={{background:colours[s.tone]}}/>{s.tone}</span><b>{s.count}<small>{percent[i]}%</small></b></div>)}</div></div><p className="sv-footnote">{total?"Automated interpretation; read alongside the original comments.":"Your sentiment breakdown will appear when written feedback arrives."}</p></section></div>
      <section className="sv-section" id="themes" data-view-section="overview"><div className="sv-section-title"><div><p className="sv-eyebrow">RECURRING THEMES</p><h2>What’s coming up?</h2></div><span className="sv-muted">A comment may mention more than one theme</span></div><div className="sv-theme-grid">{themes.filter(t=>t.items.length>1).map(t=><a href={`${base}?range=${days}&section=inbox&theme=${encodeURIComponent(t.name)}#inbox`} className="sv-card sv-theme" key={t.name}><span className={`sv-pill ${t.dominant}`}>{t.dominant} signals</span><h3>{t.name}</h3><b>{t.items.length}<small> mentions</small></b><p>{delta(t.items.length,t.previous)}</p><p className="sv-excerpt">“{t.items[0].text.slice(0,100)}{t.items[0].text.length>100?"…":""}”</p><span className="sv-link">Read related feedback →</span></a>)}</div>{!themes.some(t=>t.items.length>1)&&<p className="sv-empty">Recurring themes appear when at least two comments mention the same topic.</p>}<p className="sv-footnote">{themes.some(t=>t.items.length===1)&&`One-off observations: ${themes.filter(t=>t.items.length===1).map(t=>t.name).join(" · ")}`}</p></section>
      <section className="sv-section" id="voice" data-view-section="overview"><div className="sv-section-title"><div><p className="sv-eyebrow">CUSTOMER VOICE</p><h2>The words behind the numbers</h2></div><a href={`${base}?range=${days}&section=inbox#inbox`}>View all feedback →</a></div><div className="sv-voice-grid">{selected.map(x=><a className="sv-card sv-quote" key={x.key} href={x.href}><div><span className={`sv-pill ${x.analysis.sentiment}`}>{x.analysis.sentiment}</span><time>{date(x.created)}</time></div><blockquote>“{x.text}”</blockquote><p>{x.source} · {x.analysis.themes.join(", ")}</p><small>{x.status}{x.requested?" · Contact requested":""}</small></a>)}</div>{!selected.length&&<p className="sv-empty">Customer comments will appear here once feedback arrives.</p>}</section>
      <section className="sv-section" id="inbox" tabIndex={-1} data-view-section="inbox google"><div className="sv-section-title sv-inbox-heading"><div><p className="sv-muted">{view==="google"?"Imported Google reviews and replies.":"Outstanding messages and feedback from this reporting period."}</p></div>{view==="inbox"&&<a href="/api/manager/export">Export private feedback</a>}</div><div className="sv-filters"><label>Show<select id="sv-priority-filter" defaultValue={query.view==="attention"?"priority":query.view==="contact"?"contact":"all"}><option value="all">All feedback</option><option value="priority">Needs attention</option><option value="contact">Contact requested</option><option value="overdue">Overdue</option></select></label><label style={view==="google"?{display:"none"}:undefined}>Source<select id="sv-source-filter" defaultValue={query.source==="google"?"google":"all"}><option value="all">All sources</option><option value="private">Private feedback</option><option value="google">Google reviews</option></select></label><label className="sv-advanced-filter">Sentiment<select id="sv-sentiment-filter"><option value="all">All sentiments</option>{tones.map(t=><option key={t}>{t}</option>)}</select></label><label className="sv-advanced-filter">Status<select id="sv-status-filter"><option value="all">All statuses</option><option value="new">New</option><option value="reviewed">In progress</option><option value="resolved">Resolved</option><option value="archived">Archived</option><option value="reply-needed">Reply needed</option><option value="published">Replied</option></select></label><label className="sv-advanced-filter">Theme<select id="sv-theme-filter" defaultValue={themeNames.includes(query.theme??"")?query.theme:"all"}><option value="all">All themes</option>{[...new Set([...feedback.map(classify),...reviews.map(x=>classifyComment(x.comment??"",x.rating))].flatMap(x=>x.themes))].sort().map(t=><option key={t}>{t}</option>)}</select></label><label className="sv-search-filter">Search comments<input type="search" id="sv-search" placeholder="Search messages…"/></label><button type="button" className="sv-more-filters" id="sv-more-filters" aria-expanded="false">More filters</button></div>
      <p className="sv-footnote" id="sv-result-count" role="status"/><div className="sv-inbox">{feedback.filter(x=>inPeriod(x.created_at)||!closed(x.status)).sort((a,b)=>Number(urgent.includes(b))-Number(urgent.includes(a))).map(x=>{const a=classify(x);return <details className="sv-message" key={x.id} id={`item-${x.id}`} data-inbox-item data-source="private" data-tone={a.sentiment} data-state={x.status} data-themes={JSON.stringify(a.themes)} data-priority={urgent.includes(x)?"yes":"no"} data-contact={x.contact_requested&&!x.contacted_at&&!closed(x.status)?"yes":"no"} data-overdue={x.due_at&&x.due_at<end&&!closed(x.status)?"yes":"no"} data-search={x.message.toLowerCase()}><summary><span className={`sv-message-icon ${a.sentiment}`}><MessageSquare size={19}/></span><div><div className="sv-message-meta"><b>{x.customer_name||"Anonymous customer"}</b><span>Private feedback · {date(x.created_at)}</span></div><p>{x.message}</p><div className="sv-tags"><span className={`sv-pill ${a.sentiment}`}>{a.sentiment}</span><span>{x.status==="reviewed"?"In progress":x.status}</span>{Boolean(x.contact_requested)&&!x.contacted_at&&!closed(x.status)&&<span>Contact requested</span>}{x.severity!=="normal"&&<span>Flagged</span>}{x.due_at&&x.due_at<end&&!closed(x.status)&&<span>Overdue</span>}</div></div><span aria-hidden="true">＋</span></summary><div className="sv-message-body"><p>{x.message}</p><p className="sv-muted">{a.themes.join(" · ")}</p>{Boolean(x.contact_requested)&&x.customer_email&&<a className="sv-button secondary" href={`mailto:${x.customer_email}`}>Email customer</a>}<label>Private team note<textarea data-note-for={x.id} defaultValue={x.internal_note??""} maxLength={1000}/></label><div className="sv-actions"><button data-feedback-id={x.id} data-feedback-status="reviewed">Mark in progress</button><button data-feedback-id={x.id} data-feedback-status="resolved">Resolve</button><button data-feedback-id={x.id} data-feedback-action="note">Save note</button>{Boolean(x.contact_requested)&&!x.contacted_at&&<button data-feedback-id={x.id} data-feedback-action="contacted">Mark contacted</button>}<button data-feedback-id={x.id} data-feedback-status={x.status==="archived"?"new":"archived"}>{x.status==="archived"?"Restore":"Archive"}</button></div><p role="status"/></div></details>})}
      {reviews.filter(x=>inPeriod(x.google_created_at)||pending.includes(x)).map(x=>{const a=classifyComment(x.comment??"",x.rating);return <details className="sv-message" key={x.id} id={`review-${x.id}`} data-inbox-item data-source="google" data-tone={a.sentiment} data-state={x.reply_comment?"published":"reply-needed"} data-themes={JSON.stringify(a.themes)} data-priority={pending.includes(x)?"yes":"no"} data-contact="no" data-overdue="no" data-search={(x.comment??"").toLowerCase()}><summary><span className="sv-message-icon"><Star size={19}/></span><div><div className="sv-message-meta"><b>{x.reviewer_name||"Google customer"}</b><span>Google review · {date(x.google_created_at)}</span></div><p>{x.comment||"Rating only"}</p><div className="sv-tags"><span>{x.rating}/5 stars</span><span className={`sv-pill ${a.sentiment}`}>{a.sentiment}</span><span>{x.reply_comment?"Replied":x.reply_status==="failed"?"Reply failed":"Reply needed"}</span></div></div><span aria-hidden="true">＋</span></summary><div className="sv-message-body"><p>{x.comment||"No written comment"}</p>{x.reply_comment&&<blockquote><b>Your published reply</b><p>{x.reply_comment}</p></blockquote>}<form className="review-reply" data-review-id={x.id}><button type="button" className="sv-button secondary" data-draft-review={x.id}>Suggest a reply</button><label>Review and edit your reply<textarea required minLength={2} maxLength={4096} defaultValue={x.reply_comment??""} placeholder="Write a thoughtful reply to this customer…"/></label><small>Your reply will be public on Google.</small><button className="sv-button" disabled={!connected}>Publish reply</button><span role="status"/></form>{!connected&&<a href={`${base}?range=${days}&source=google#google`}>Reconnect Google to publish a reply</a>}</div></details>})}</div><p id="sv-empty-inbox" className="sv-empty" hidden>{view==="google"&&!available?"No Google reviews have been synced yet. Connect Google to bring them into this inbox.":"No feedback matches these filters. Try another filter or reporting period."}</p></section>
      <div className="sv-analysis-grid sv-service-views" data-view-container><section className="sv-card" id="google" data-view-section="google"><p className="sv-eyebrow">GOOGLE BUSINESS PROFILE</p><h2>{googleMessage}</h2>{available?<><p>{reviews.length} imported reviews · {pending.length} awaiting replies</p><p className="sv-muted">Imported review average: {reviews.length?(reviews.reduce((s,x)=>s+x.rating,0)/reviews.length).toFixed(1):"—"}/5. This may differ from your public Google rating.</p><p className="sv-muted">Last successful sync: {c?.last_synced_at?new Date(c.last_synced_at).toLocaleString("en-GB"):"Not yet"}</p></>:<p>Bring your Google reviews into one inbox, spot trends and publish replies you approve. Sign in with the Google account that manages your business.</p>}<a className="sv-button" href={connected?"/api/google/sync":"/api/google/connect"}>{connected?"Sync reviews now":"Connect Google Business Profile"}</a><p className="sv-footnote">{connected?"You control every reply published on Google.":"Connection becomes available when StreetVouch’s Google integration is enabled. No password is shared with StreetVouch."}</p></section><section className="sv-card" id="report" data-view-section="reports"><p className="sv-eyebrow">YOUR WEEKLY BRIEFING</p><h2>Useful insights, in your inbox.</h2><p>Your weekly email brings together activity, sentiment, recurring themes and follow-ups.</p><button className="sv-button secondary" id="manager-send-summary">Email weekly report</button><p id="manager-summary-status" role="status" tabIndex={-1}/><p className="sv-footnote">Sends the weekly report to your signed-in email address.</p><ul className="sv-deliveries">{reports.results.map((x,i)=><li key={i}><time>{date(x.created_at)}</time><span>{x.status}</span></li>)}</ul></section></div>
      <section className="sv-next" data-view-section="overview"><span><Check size={22}/></span><div><p className="sv-eyebrow">RECOMMENDED NEXT STEPS</p>{waiting.length>0&&<p><a href={`${base}?range=${days}&section=inbox&view=contact#inbox`}>Follow up with {waiting.length} {waiting.length===1?"customer":"customers"} who requested contact.</a></p>}{pending.length>0&&<p><a href={`${base}?range=${days}&source=google&view=attention#inbox`}>Review and reply to {pending.length} unanswered Google reviews.</a></p>}{themes.find(t=>t.dominant==="negative"&&t.items.length>1)?<p>Discuss {themes.find(t=>t.dominant==="negative"&&t.items.length>1)!.name.toLowerCase()} with your team: it appears in {themes.find(t=>t.dominant==="negative"&&t.items.length>1)!.items.length} comments.</p>:themes.find(t=>t.dominant==="positive"&&t.items.length>1)?<p>Share the praise for {themes.find(t=>t.dominant==="positive"&&t.items.length>1)!.name.toLowerCase()} with your team.</p>:<p>{urgent.length?"Read the flagged and negative comments to decide the next follow-up.":"Keep your NFC tags visible and invite customers to share honest feedback."}</p>}</div></section>
      <footer className="sv-footer">StreetVouch · Feedback made useful.<a href={`${base}/onboarding`}>Business settings</a></footer>
    </div></main><Script src="/manager.js" strategy="afterInteractive"/><Script src="/manager-dashboard.js" strategy="afterInteractive"/></>;
}
