import { env } from "cloudflare:workers";
import { redirect } from "next/navigation";
import Script from "next/script";
import { getManagerSession } from "../../../manager-auth";
export const dynamic="force-dynamic";
type Row={id:string;name:string;slug:string;status:string;logo_url:string|null;address:string|null;category:string|null;contact_email:string|null;phone:string|null;website:string|null;opening_hours:string|null;customer_heading:string;customer_intro:string;customer_private_prompt:string;page_approved:number;google_status:string;google_location_title:string|null;last_synced_at:string|null;business_details_complete:number;manager_account_active:number;google_connection_tested:number;customer_page_approved:number;nfc_tested:number;qr_tested:number;private_feedback_tested:number;notification_email_tested:number;pilot_activated:number;last_report_sent_at:string|null};
export default async function ManagerOnboarding({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<Record<string,string|undefined>>}){const {slug}=await params,query=await searchParams,session=await getManagerSession();if(!session)redirect(`/manager/${slug}`);if(session.businessSlug!==slug)return <main className="manager-denied"><h1>Access restricted</h1><p>This account cannot access another business.</p></main>;if(!env.DB)throw new Error("Database unavailable");const row=await env.DB.prepare(`SELECT b.*,COALESCE(gc.status,'not_connected') google_status,gc.google_location_title,gc.last_synced_at,oc.business_details_complete,oc.manager_account_active,oc.google_connection_tested,oc.customer_page_approved,oc.nfc_tested,oc.qr_tested,oc.private_feedback_tested,oc.notification_email_tested,oc.pilot_activated FROM businesses b LEFT JOIN google_connections gc ON gc.business_id=b.id LEFT JOIN onboarding_checks oc ON oc.business_id=b.id WHERE b.id=?`).bind(session.businessId).first<Row>();if(!row)return <main>Business unavailable.</main>;const checks=[['Business details',row.business_details_complete],['Manager account',row.manager_account_active],['Google connection',row.google_connection_tested],['Customer page approval',row.customer_page_approved],['NFC test',row.nfc_tested],['QR test',row.qr_tested],['Private feedback test',row.private_feedback_tested],['Notification email test',row.notification_email_tested]] as const,done=checks.filter(([,value])=>value).length;return <><link rel="stylesheet" href="/manager.css"/><link rel="stylesheet" href="/onboarding.css"/><link rel="stylesheet" href="/manager-onboarding.css"/><link rel="stylesheet" href="/owner-nav.css"/><main className="manager-shell onboarding-manager" data-manager-onboarding>
  {query.from==='admin'&&<a className="back-to-admin" href={`/admin/onboarding?business=${slug}`}>← Back to business portal</a>}<header className="manager-header"><a className="manager-brand" href={`/manager/${slug}`}><span>✓</span>streetvouch</a><nav className="manager-nav"><a href={`/manager/${slug}`}>Overview</a><a className="active" href={`/manager/${slug}/onboarding`}>Setup</a></nav><div><span>{row.name}</span><form action="/api/manager/logout" method="post"><button>Sign out</button></form></div></header>
  <section className="manager-hero compact"><div><span className="kicker">SETUP &amp; INTEGRATIONS</span><h1>{done===8?'Your setup is complete.':'Finish your setup.'}</h1><p>{done} of 8 checks complete. Setup stays inside your owner portal so you can return whenever details or integrations change.</p></div><strong className="progress-number">{done}/8</strong></section><p id="manager-onboarding-status" className="manager-status" role="status"></p>
  <section className="manager-grid"><article className="manager-card"><span className="kicker">SETUP PROGRESS</span><h2>Before the pilot starts</h2><ul className="manager-checks">{checks.map(([label,value])=><li key={label} className={value?'done':''}><span>{value?'✓':'○'}</span><b>{label}</b></li>)}</ul></article><article className="manager-card google-card"><span className="kicker">GOOGLE BUSINESS PROFILE</span><h2>{googleLabel(row.google_status)}</h2><p>{row.google_location_title?`Selected location: ${row.google_location_title}`:'Connect the Google account that manages this exact business. You will choose the location before anything syncs.'}</p>{row.google_status==='connected'?<><small>Last tested {row.last_synced_at?new Date(row.last_synced_at).toLocaleString('en-GB'):'not yet'}</small><a className="manager-secondary" href="/api/google/sync">Test review sync</a></>:<a className="manager-primary inline" href="/api/google/connect">Connect Google securely</a>}</article></section>
  <section className="manager-content page-review"><div className="content-heading"><div><span className="kicker">CUSTOMER PAGE</span><h2>Review the wording</h2></div><a className="manager-secondary" href={`/customer/${slug}?test=1`} target="_blank">Open safe preview</a></div><form id="manager-page-form"><label>Customer heading<input name="customerHeading" defaultValue={row.customer_heading}/></label><label>Introduction<textarea name="customerIntro" defaultValue={row.customer_intro}/></label><label>Private feedback prompt<input name="customerPrivatePrompt" defaultValue={row.customer_private_prompt}/></label><div><button name="save" className="manager-secondary">Save draft</button><button name="approve" className="manager-primary">Approve customer page</button></div></form><p className="honesty-panel"><b>Honest and balanced by design.</b> Every visitor sees both the public-review and private-feedback options. StreetVouch does not ask for a rating first, hide negative experiences or publish anything during safe preview.</p></section>
  <section className="manager-grid"><article className="manager-card"><span className="kicker">FIRST WEEK</span><h2>Summary status</h2><p>{row.last_report_sent_at?`Latest report sent ${new Date(row.last_report_sent_at).toLocaleDateString('en-GB')}.`:'Your first-week summary will appear after the pilot has collected genuine activity. No test data is included.'}</p></article><article className="manager-card"><span className="kicker">HANDOFF</span><h2>{row.status==='active'?'Pilot is active':row.status==='completed'?'Onboarding complete':row.status.replaceAll('_',' ')}</h2><p>{row.status==='completed'?'Setup has been handed over. Your reports and customer activity remain available.':'StreetVouch will activate the pilot only when all required checks have passed.'}</p></article></section>
  </main><Script src="/manager-onboarding.js" strategy="afterInteractive"/></>}
function googleLabel(status:string){return ({not_connected:'Not connected',awaiting_authorisation:'Awaiting authorisation',pending:'Choose the correct location',connected:'Connected',sync_failed:'Sync failed',reauthorisation_required:'Reauthorisation required',needs_attention:'Needs attention',disconnected:'Not connected'} as Record<string,string>)[status]??'Not connected'}
