import Link from "next/link";

export type CustomerBusiness={id:string;slug:string;name:string;logo_url:string|null;category:string|null;customer_heading:string;customer_intro:string;customer_private_prompt:string;google_review_url:string;status:string;page_approved:number};

export function CustomerPageView({business,test=false,asset="",entryChannel=""}:{business:CustomerBusiness;test?:boolean;asset?:string;entryChannel?:"nfc"|"qr"|""}){return <><link rel="stylesheet" href="/style.css"/><link rel="stylesheet" href="/customer-business.css?v=direct-tag-1"/><main className="customer-business" data-business={business.slug}>
  {test&&<div className="demo-banner">Safe test mode · no review, feedback, notification or tracking data can be sent.</div>}<section className="customer-business-card"><div className="customer-logo">{business.logo_url?<img src={business.logo_url} alt={`${business.name} logo`} fetchPriority="high"/>:<span>{business.name.slice(0,1)}</span>}</div><span className="shop-name">{business.name}</span><small>{business.category??"Local business"}</small><h1>{business.customer_heading}</h1><p>{business.customer_intro}</p><div id="customer-journey"><button className="choice choice-primary" id="customer-google"><span><b>Leave a Google review</b><small>Share an honest account of your experience</small></span><span className="arrow">↗</span></button><div className="private-route"><span>{business.customer_private_prompt}</span><button id="customer-private">Send private feedback</button></div><p className="honesty-note">Both options are always available. StreetVouch does not filter by rating.</p></div><div className="powered">Feedback made simple with <Link className="brand" href="/"><span className="mark">✓</span>streetvouch</Link></div></section>
  <script id="customer-config" type="application/json" dangerouslySetInnerHTML={{__html:JSON.stringify({name:business.name,slug:business.slug,googleReviewUrl:business.google_review_url,test,asset,entryChannel}).replaceAll("<","\\u003c")}}/>
  </main><script src="/customer-business.js?v=direct-tag-1" defer/></>}

export function CustomerUnavailable(){return <main className="customer-unavailable"><h1>This feedback page is not active yet.</h1><p>Please contact the business directly if you would like to share feedback.</p></main>}
