import { env } from "cloudflare:workers";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import Script from "next/script";
import { adminAllowed } from "../../api/_shared";
export const dynamic="force-dynamic";

type Business={id:string;slug:string;name:string;status:string;logo_url:string|null;contact_email:string|null;phone:string|null;website:string|null;opening_hours:string|null;google_profile_url:string|null;google_review_url:string;customer_heading:string;customer_intro:string;customer_private_prompt:string;category:string|null;address:string|null;manager_active:number;google_status:string|null;page_approved:number;business_details_complete:number;manager_account_active:number;google_connection_tested:number;customer_page_approved:number;nfc_tested:number;qr_tested:number;private_feedback_tested:number;notification_email_tested:number;pilot_activated:number;visits:number;nfc_taps:number;qr_scans:number;google_clicks:number;private_feedback:number;reviews:number;active_assets:number;pilot_started_at:string|null;pilot_completed_at:string|null};

export default async function OnboardingPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const h=await headers();if(!h.get("oai-authenticated-user-email"))redirect("/signin-with-chatgpt?return_to=%2Fadmin%2Fonboarding");if(!adminAllowed(h))return <main className="admin-denied"><h1>Access restricted</h1></main>;if(!env.DB)throw new Error("Database unavailable");
  const params=await searchParams, result=await env.DB.prepare(`SELECT b.id,b.slug,b.name,b.status,b.logo_url,b.contact_email,b.phone,b.website,b.opening_hours,b.google_profile_url,b.google_review_url,b.customer_heading,b.customer_intro,b.customer_private_prompt,b.category,b.address,b.page_approved,b.pilot_started_at,b.pilot_completed_at,
    EXISTS(SELECT 1 FROM manager_users mu WHERE mu.business_id=b.id AND mu.active=1) manager_active,
    COALESCE(gc.status,'not_connected') google_status,
    COALESCE(oc.business_details_complete,0) business_details_complete,COALESCE(oc.manager_account_active,0) manager_account_active,COALESCE(oc.google_connection_tested,0) google_connection_tested,COALESCE(oc.customer_page_approved,0) customer_page_approved,COALESCE(oc.nfc_tested,0) nfc_tested,COALESCE(oc.qr_tested,0) qr_tested,COALESCE(oc.private_feedback_tested,0) private_feedback_tested,COALESCE(oc.notification_email_tested,0) notification_email_tested,COALESCE(oc.pilot_activated,0) pilot_activated,
    (SELECT COUNT(*) FROM events e WHERE e.business_id=b.id AND e.event_type='page_view') visits,(SELECT COUNT(*) FROM events e WHERE e.business_id=b.id AND e.event_type='nfc_tap') nfc_taps,(SELECT COUNT(*) FROM events e WHERE e.business_id=b.id AND e.event_type='qr_scan') qr_scans,(SELECT COUNT(*) FROM events e WHERE e.business_id=b.id AND e.event_type='google_click') google_clicks,(SELECT COUNT(*) FROM feedback f WHERE f.business_id=b.id) private_feedback,(SELECT COUNT(*) FROM google_reviews gr WHERE gr.business_id=b.id) reviews,(SELECT COUNT(*) FROM business_assets ba WHERE ba.business_id=b.id AND ba.active=1) active_assets
    FROM businesses b LEFT JOIN google_connections gc ON gc.business_id=b.id LEFT JOIN onboarding_checks oc ON oc.business_id=b.id ORDER BY b.created_at DESC`).all<Business>();
  const selected=result.results.find(b=>b.slug===params.business)??result.results[0];
  return <><link rel="stylesheet" href="/admin.css"/><link rel="stylesheet" href="/onboarding.css"/><link rel="stylesheet" href="/onboarding-details.css"/><main className="admin-shell onboarding-shell">
    <header><div><span className="admin-brand">✓ streetvouch</span><p>Business portal</p></div><a href="/admin">Back to businesses</a></header>
    <section className="admin-title"><div><span>BUSINESS SETUP</span><h1>Accounts and activation.</h1><p>Create a business, invite its owner and confirm the customer page and physical touchpoints before launch.</p></div><button className="export" data-open-create>Add business</button></section>
    <p className="admin-status" id="onboarding-status" role="status"></p>
    <section className="pipeline">{["setup","awaiting_approval","active","paused","completed"].map(status=><article key={status}><b>{result.results.filter(b=>b.status===status).length}</b><span>{status.replaceAll("_"," ")}</span></article>)}</section>
    <section className="business-grid">{result.results.map(b=><a key={b.id} className={`business-tile ${selected?.id===b.id?"selected":""}`} href={`/admin/onboarding?business=${b.slug}`}><div><b>{b.name}</b><span>{b.status.replaceAll("_"," ")}</span></div><strong>{[b.business_details_complete,b.manager_account_active,b.google_connection_tested,b.customer_page_approved,b.nfc_tested,b.qr_tested,b.private_feedback_tested,b.notification_email_tested].filter(Boolean).length}/8</strong><small>{b.active_assets} assets · {b.google_status.replaceAll("_"," ")}</small></a>)}</section>
    {selected?<BusinessWorkspace business={selected}/>:<div className="empty">Create the first business to begin onboarding.</div>}
    <dialog id="create-business"><form id="business-create" className="onboarding-form"><button type="button" className="dialog-x" data-close-create>×</button><span className="kicker">NEW BUSINESS</span><h2>Create the workspace</h2><label>Business name<input name="name" required/></label><label>Contact email<input name="contactEmail" type="email" required/></label><label>Category<input name="category" placeholder="Café, salon, shop…"/></label><label>Address<textarea name="address"/></label><button className="manager-primary">Create business</button><p role="status"></p></form></dialog>
  </main><Script src="/onboarding.js" strategy="afterInteractive"/></>;
}

function BusinessWorkspace({business:b}:{business:Business}){const checks=[['business_details_complete','Business details complete',b.business_details_complete],['manager_account_active','Manager account active',b.manager_account_active],['google_connection_tested','Google connection tested',b.google_connection_tested],['customer_page_approved','Customer page approved',b.customer_page_approved],['nfc_tested','NFC tested',b.nfc_tested],['qr_tested','QR code tested',b.qr_tested],['private_feedback_tested','Private feedback tested',b.private_feedback_tested],['notification_email_tested','Notification email tested',b.notification_email_tested]] as const;return <section className="onboarding-workspace" data-business-id={b.id}>
  <div className="workspace-head"><div><span className="kicker">{b.status.replaceAll('_',' ')}</span><h2>{b.name}</h2><p>{b.category??"Category not set"} · {b.address??"Address not set"}</p></div><div className="workspace-actions"><a className="export" href={`/manager/${b.slug}?from=admin`}>Preview owner portal</a><a className="export" href={`/customer/${b.slug}?test=1`} target="_blank">Preview customer page</a></div></div>
  <section className="setup-card business-details-card"><span className="kicker">BUSINESS SETUP</span><h3>Profile and customer-page content</h3><form id="business-details-form" className="details-form"><label>Business name<input name="name" defaultValue={b.name} required/></label><label>Logo URL<input name="logoUrl" type="url" defaultValue={b.logo_url??''}/></label><label>Category<input name="category" defaultValue={b.category??''} required/></label><label>Contact email<input name="contactEmail" type="email" defaultValue={b.contact_email??''} required/></label><label>Phone<input name="phone" type="tel" defaultValue={b.phone??''} required/></label><label>Website<input name="website" type="url" defaultValue={b.website??''}/></label><label className="wide">Address<textarea name="address" defaultValue={b.address??''} required/></label><label className="wide">Opening hours<textarea name="openingHours" defaultValue={b.opening_hours??''} placeholder="Mon–Fri 09:00–17:30"/></label><label className="wide">Google Business Profile URL<input name="googleProfileUrl" type="url" defaultValue={b.google_profile_url??''} required/></label><label className="wide">Google review URL<input name="googleReviewUrl" type="url" defaultValue={b.google_review_url}/></label><label className="wide">Customer-page heading<input name="customerHeading" defaultValue={b.customer_heading}/></label><label className="wide">Customer-page introduction<textarea name="customerIntro" defaultValue={b.customer_intro}/></label><label className="wide">Private-feedback prompt<input name="customerPrivatePrompt" defaultValue={b.customer_private_prompt}/></label><button>Save business details</button><output></output></form></section>
  <div className="onboarding-grid"><section className="setup-card"><span className="kicker">ACTIVATION CHECKLIST</span><h3>Required before launch</h3><div className="check-list">{checks.map(([key,label,value])=><label key={key}><input type="checkbox" data-check={key} defaultChecked={Boolean(value)}/><span><b>{label}</b><small>{label.includes('tested')?'Confirm only after a real controlled test.':'Required for activation.'}</small></span></label>)}</div><div className="pilot-actions"><button data-pilot="activate">Activate pilot</button><button data-pilot="pause">Pause</button><button data-pilot="complete">Complete and hand off</button></div></section>
  <section className="setup-stack"><article className="setup-card"><span className="kicker">MANAGER ACCESS</span><h3>{b.manager_active?'Manager active':'Invite the owner'}</h3><form id="manager-invite"><label>Email<input name="email" type="email" defaultValue={b.contact_email??''} required/></label><label>Name<input name="displayName"/></label><button>Create secure invitation</button><output id="invitation-output"></output></form></article><article className="setup-card"><span className="kicker">PHYSICAL ASSETS</span><h3>{b.active_assets} active assets</h3><form id="asset-create"><label>Label<input name="label" placeholder="Front counter" required/></label><label>Placement<input name="placement" placeholder="Beside card terminal" required/></label><label>Type<select name="assetType"><option value="counter">Counter</option><option value="barber_station">Barber station</option><option value="window">Window</option><option value="card">Card</option><option value="other">Other</option></select></label><button>Create asset URLs</button><output id="asset-output"></output></form></article></section></div>
  <section className="pilot-metrics"><article><b>{b.active_assets}</b><span>active assets</span></article><article><b>{b.visits}</b><span>page visits</span></article><article><b>{b.nfc_taps}</b><span>NFC taps</span></article><article><b>{b.qr_scans}</b><span>QR scans</span></article><article><b>{b.google_clicks}</b><span>Google clicks</span></article><article><b>{b.private_feedback}</b><span>private feedback</span></article><article><b>{b.reviews}</b><span>reviews</span></article></section>
  <details className="nfc-help"><summary>How to prepare and test an NFC asset</summary><ol><li>Create the labelled asset above.</li><li>Encode the exact NFC URL—never a direct Google link.</li><li>Lock the tag only after opening it successfully on a second phone.</li><li>Generate the QR from the separate QR payload.</li><li>Use safe preview mode for testing; it cannot publish a review or store feedback.</li><li>Mark NFC and QR tested only after each destination has been checked.</li></ol></details>
</section>}
