import { env } from "cloudflare:workers";
import { allow, anonymousKey, BUSINESS, db, ensureBusiness, json, sameOrigin } from "../../_shared";
import { hashPassword, hashToken, randomHex } from "../../../manager-auth";

export async function POST(request:Request){
  try{
    if(!sameOrigin(request))return json({ok:false,message:"Account creation could not be completed."},403);
    const body=await request.json() as {email?:string;password?:string;confirmation?:string;website?:string};if(body.website)return json({ok:true,message:"Check your inbox to confirm your email."});
    const email=body.email?.trim().toLowerCase()??"",password=body.password??"";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json({ok:false,message:"Enter a valid email address."},400);if(password!==body.confirmation)return json({ok:false,message:"The passwords do not match."},400);if(password.length<10||!/[A-Za-z]/.test(password)||!/[0-9]/.test(password))return json({ok:false,message:"Use at least 10 characters, including a letter and a number."},400);
    const database=db();await ensureBusiness(database);const rateKey=`manager-signup:${await anonymousKey(request,"manager-signup")}`;if(!await allow(database,rateKey,5,3600))return json({ok:false,message:"Too many attempts. Please try again later."},429);
    const authorised=(env.OWNER_EMAIL??"").trim().toLowerCase();if(!authorised||email!==authorised)return json({ok:true,message:"If this email is authorised, a confirmation message is on its way."});
    const existing=await database.prepare("SELECT id,active,password_hash FROM manager_users WHERE business_id=? AND email=?").bind(BUSINESS.id,email).first<{id:string;active:number;password_hash:string|null}>();if(existing?.active&&existing.password_hash)return json({ok:false,message:"An account already exists for this email. Sign in or use Forgot password."},409);
    const managerId=existing?.id??crypto.randomUUID(),now=new Date(),salt=randomHex(),passwordHash=await hashPassword(password,salt);if(existing)await database.prepare("UPDATE manager_users SET active=0 WHERE id=?").bind(managerId).run();else await database.prepare("INSERT INTO manager_users (id,business_id,email,display_name,role,active,created_at) VALUES (?,?,?,?, 'owner',0,?)").bind(managerId,BUSINESS.id,email,"Village Barbers manager",now.toISOString()).run();
    const token=crypto.randomUUID()+crypto.randomUUID().replaceAll("-",""),tokenHash=await hashToken(token),expires=new Date(now.getTime()+30*60*1000).toISOString();await database.prepare("INSERT INTO manager_login_tokens (token_hash,manager_user_id,purpose,pending_password_hash,pending_password_salt,expires_at,created_at) VALUES (?,?,'signup',?,?,?,?)").bind(tokenHash,managerId,passwordHash,salt,expires,now.toISOString()).run();
    if(!env.RESEND_API_KEY)return json({ok:false,message:"Confirmation email is temporarily unavailable."},503);const link=`${new URL(request.url).origin}/api/manager/confirm-signup?token=${encodeURIComponent(token)}`,response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from:env.EMAIL_FROM??"StreetVouch <onboarding@resend.dev>",to:[email],subject:"Confirm your StreetVouch account",html:`<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto;padding:32px;color:#142829"><div style="font-weight:800;font-size:20px;margin-bottom:28px">✓ streetvouch</div><h1 style="font-family:Georgia,serif;font-size:34px">Confirm your manager account</h1><p>Confirm this email address to activate the Village Barbers Cobham dashboard account. This link expires in 30 minutes.</p><p style="margin:28px 0"><a href="${link}" style="background:#142829;color:#fff;text-decoration:none;padding:14px 20px;border-radius:10px;font-weight:700">Confirm account</a></p><p style="color:#617170;font-size:13px">If you didn’t create this account, you can ignore this email.</p></div>`})});if(!response.ok)throw new Error(`Email service returned ${response.status}`);return json({ok:true,message:"Check your inbox and confirm your email to finish creating the account."});
  }catch(error){console.error("manager_signup_failed",error);return json({ok:false,message:"We couldn’t create the account. Please try again."},503);}
}
