import { env } from "cloudflare:workers";
import Script from "next/script";
import { BUSINESS } from "../../api/_shared";
import { getManagerSession, getPasswordResetSession } from "../../manager-auth";
import Dashboard from "../dashboard";
export const dynamic="force-dynamic";
export default async function ManagerDashboard({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const query=await searchParams,session=await getManagerSession(),reset=query.password==="reset"?await getPasswordResetSession():null;
 if(reset)return <PasswordSetup/>;
 if(!session)return <ManagerSignIn fromAdmin={query.from==="admin"}/>;
 if(session.businessId!==BUSINESS.id)return <main><h1>Access restricted</h1></main>;
 if(!env.DB)throw new Error("Database unavailable");
 return <Dashboard session={{...session,businessSlug:"village-barbers-cobham"}} query={query}/>;
}

function ManagerSignIn({fromAdmin=false}:{fromAdmin?:boolean}){const linkStyle={color:"var(--ink)",fontWeight:800,textDecoration:"none"};return <><link rel="stylesheet" href="/manager.css"/><link rel="stylesheet" href="/manager-extra.css"/><main className="manager-login">{fromAdmin&&<a className="back-to-admin login-back" href="/admin">← Back to StreetVouch admin</a>}<div className="login-brand"><span>✓</span>streetvouch</div><div className="login-card"><img src="/village-barbers-logo.jpeg" alt="Village Barbers Cobham"/><span className="kicker">VILLAGE BARBERS COBHAM</span><h1>Manager sign in.</h1><p>Use the email address and password registered for this shop.</p><form id="manager-login"><label htmlFor="manager-email">Email address</label><input id="manager-email" type="email" required autoComplete="email" placeholder="you@example.com"/><label htmlFor="manager-password">Password</label><input id="manager-password" type="password" required autoComplete="current-password"/><div className="login-trap" aria-hidden="true"><input id="manager-website" tabIndex={-1} autoComplete="off"/></div><button type="submit">Sign in</button><p id="login-status" role="status"></p></form><nav aria-label="Account help" style={{display:"flex",justifyContent:"space-between",gap:16,borderTop:"1px solid var(--line)",paddingTop:18,marginTop:8,fontSize:14}}><a href="/manager/village-barbers-cobham/signup" style={linkStyle}>Create account</a><a href="/manager/village-barbers-cobham/forgot-password" style={linkStyle}>Forgot password?</a></nav></div><small>Private access for the Village Barbers Cobham management team.</small></main><Script src="/manager.js" strategy="afterInteractive"/></>}
function PasswordSetup(){return <><link rel="stylesheet" href="/manager.css"/><main className="manager-login"><div className="login-brand"><span>✓</span>streetvouch</div><div className="login-card"><img src="/village-barbers-logo.jpeg" alt="Village Barbers Cobham"/><span className="kicker">SECURE MANAGER ACCESS</span><h1>Choose a password.</h1><p>Use at least 10 characters, including a number. You’ll use this for everyday sign-in.</p><form id="manager-set-password"><label htmlFor="new-password">New password</label><input id="new-password" type="password" required minLength={10} autoComplete="new-password"/><label htmlFor="confirm-password">Confirm password</label><input id="confirm-password" type="password" required minLength={10} autoComplete="new-password"/><button>Save password</button><p id="login-status" role="status"></p></form></div></main><Script src="/manager.js" strategy="afterInteractive"/></>}
