import { env } from "cloudflare:workers";
import Script from "next/script";
import { BUSINESS, ensureBusiness } from "../../api/_shared";
import { getManagerSession, getPasswordResetSession } from "../../manager-auth";
import { syncGoogleReviews } from "../../google";
export const dynamic="force-dynamic";

type Feedback={id:string;customer_name:string|null;customer_email:string|null;message:string;contact_requested:number;severity:string;status:string;contacted_at:string|null;internal_note:string|null;created_at:string};
type GoogleReview={id:string;reviewer_name:string|null;rating:number;comment:string|null;google_created_at:string;reply_comment:string|null;reply_status:string};
type Report={status:string;recipient_email:string;created_at:string};

export default async function ManagerDashboard({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  if(!env.DB)throw new Error("Database unavailable");await ensureBusiness(env.DB);
  const params=await searchParams,session=await getManagerSession(),resetSession=params.password==="reset"?await getPasswordResetSession():null;
  if(resetSession)return <PasswordSetup/>;if(!session)return <ManagerSignIn/>;
  if(session.businessId!==BUSINESS.id)return <main className="manager-denied"><h1>Access restricted</h1><p>This account does not have access to Village Barbers Cobham.</p></main>;
  const days=new Set(["7","30","90"]).has(params.range??"")?Number(params.range):7,since=new Date(Date.now()-days*86400000).toISOString();
  const stale=await env.DB.prepare("SELECT status,last_synced_at FROM google_connections WHERE business_id=?").bind(session.businessId).first<{status:string;last_synced_at:string|null}>();
  if(stale?.status==="connected"&&(!stale.last_synced_at||Date.now()-new Date(stale.last_synced_at).getTime()>15*60*1000)){try{await syncGoogleReviews(session.businessId)}catch(error){console.error("automatic_google_sync_failed",error)}}
  const [feedbackResult,eventResult,reviewsResult,connection,reportsResult]=await Promise.all([
    env.DB.prepare("SELECT * FROM feedback WHERE business_id=? ORDER BY CASE WHEN status='new' THEN 0 ELSE 1 END,created_at DESC LIMIT 100").bind(session.businessId).all<Feedback>(),
    env.DB.prepare("SELECT event_type,COUNT(*) count FROM events WHERE business_id=? AND created_at>=? GROUP BY event_type").bind(session.businessId,since).all<{event_type:string;count:number}>(),
    env.DB.prepare("SELECT * FROM google_reviews WHERE business_id=? ORDER BY google_created_at DESC LIMIT 100").bind(session.businessId).all<GoogleReview>(),
    env.DB.prepare("SELECT status,last_synced_at,last_error,google_location_title FROM google_connections WHERE business_id=?").bind(session.businessId).first<{status:string;last_synced_at:string|null;last_error:string|null;google_location_title:string|null}>(),
    env.DB.prepare("SELECT status,recipient_email,created_at FROM report_deliveries WHERE business_id=? ORDER BY created_at DESC LIMIT 3").bind(session.businessId).all<Report>()
  ]);
  const feedback=feedbackResult.results,reviews=reviewsResult.results,counts=Object.fromEntries(eventResult.results.map(r=>[r.event_type,r.count]));
  const periodFeedback=feedback.filter(x=>x.created_at>=since),periodReviews=reviews.filter(x=>x.google_created_at>=since),waiting=feedback.filter(x=>x.contact_requested&&!x.contacted_at&&x.status!=="resolved"),flagged=feedback.filter(x=>x.severity!=="normal"&&x.status!=="resolved"),pendingReviews=reviews.filter(x=>x.reply_status!=="published");
  const attentionIds=new Set([...waiting,...flagged].map(x=>x.id)),visibleFeedback=params.view==="attention"?feedback.filter(x=>attentionIds.has(x.id)):feedback;
  return <><link rel="stylesheet" href="/manager.css"/><link rel="stylesheet" href="/manager-extra.css"/><main className="manager-shell">
    <header className="manager-header"><a className="manager-brand" href="/manager/village-barbers-cobham"><span>✓</span>streetvouch</a><div><span>{session.businessName}</span><form action="/api/manager/logout" method="post"><button>Sign out</button></form></div></header>
    <section className="manager-hero compact"><div><span className="kicker">CUSTOMER PULSE</span><h1>Good morning.</h1><p>Start with the items that need you. Everything else can wait.</p></div><div className="hero-actions"><form method="get"><label htmlFor="range">Showing</label><select id="range" name="range" defaultValue={String(days)}><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></select><button>Apply</button></form><button id="manager-send-summary" className="manager-primary">Email report</button></div></section>
    <p id="manager-status" className="manager-status" role="status">{params.google==="setup_required"?"Google integration is ready once API approval and credentials are added.":""}</p>
    <section className="manager-metrics"><article><b>{counts.page_view??0}</b><span>page visits</span></article><article><b>{counts.google_click??0}</b><span>Google clicks</span></article><article><b>{periodFeedback.length}</b><span>private messages</span></article><article><b>{periodReviews.length}</b><span>new Google reviews</span></article></section>
    <section className="manager-card action-queue"><div className="card-heading"><div><span className="kicker">DO THESE FIRST</span><h2>{waiting.length+flagged.length+pendingReviews.length===0?"You’re all caught up":"Needs attention"}</h2></div><strong className="queue-count">{waiting.length+flagged.length+pendingReviews.length}</strong></div><div className="queue-items"><a href="#feedback"><b>{waiting.length}</b><span>customers waiting for a reply</span></a><a href="#feedback"><b>{flagged.length}</b><span>flagged feedback items</span></a><a href="#reviews"><b>{pendingReviews.length}</b><span>reviews without a reply</span></a></div></section>
    <section className="manager-grid"><article className="manager-card google-card"><div className="card-heading"><div><span className="kicker">GOOGLE BUSINESS PROFILE</span><h2>{connection?.status==="connected"?"Reviews connected":"Connect Google reviews"}</h2></div><span className={`connection-dot ${connection?.status??"pending"}`}>{connection?.status==="connected"?"Connected":"Not connected"}</span></div>{connection?.status==="connected"?<><p>All reviews sync here, including reviews left directly through Search or Maps.</p><small>Last checked {connection.last_synced_at?new Date(connection.last_synced_at).toLocaleString("en-GB"):"recently"}</small><a className="manager-secondary" href="/api/google/sync">Sync now</a></>:<><p>Connect once to import reviews, measure growth and publish approved replies.</p><a className="manager-primary inline" href="/api/google/connect">Connect Google</a><small>Requires Google’s Business Profile API approval.</small></>}</article><article className="manager-card report-card"><span className="kicker">REPORTS</span><h2>Recent deliveries</h2>{reportsResult.results.length?<ul>{reportsResult.results.map((report,index)=><li key={index}><span>{new Date(report.created_at).toLocaleDateString("en-GB")}</span><b>{report.status}</b></li>)}</ul>:<p>Your first emailed report will appear here.</p>}</article></section>
    <section className="manager-content" id="feedback"><div className="content-heading"><div><span className="kicker">PRIVATE FEEDBACK</span><h2>Customer inbox</h2></div><nav className="simple-tabs"><a className={params.view!=="attention"?"active":""} href={`?range=${days}#feedback`}>All</a><a className={params.view==="attention"?"active":""} href={`?range=${days}&view=attention#feedback`}>Needs attention</a><a href="/api/manager/export">Export</a></nav></div>{visibleFeedback.length===0?<div className="manager-empty">No feedback in this view.</div>:<div className="manager-list">{visibleFeedback.map(item=><article className="manager-feedback" key={item.id} data-status={item.status}><div className="feedback-top"><span className={`severity ${item.severity}`}>{item.severity}</span><span>{item.status}</span><time>{new Date(item.created_at).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short"})}</time></div><p>{item.message}</p><div className="feedback-person"><span><b>{item.customer_name??"Anonymous"}</b>{item.customer_email&&<> · <a href={`mailto:${item.customer_email}`}>{item.customer_email}</a></>}</span>{item.contact_requested&&<strong>{item.contacted_at?"Customer contacted":"Reply requested"}</strong>}</div><label className="note-field">Private team note<textarea data-note-for={item.id} defaultValue={item.internal_note??""} placeholder="Add a short note…"/></label><div className="manager-actions"><button data-feedback-id={item.id} data-feedback-status="reviewed" disabled={item.status==="reviewed"}>Reviewed</button>{item.contact_requested&&!item.contacted_at&&<button data-feedback-id={item.id} data-feedback-action="contacted">Customer contacted</button>}<button data-feedback-id={item.id} data-feedback-status="resolved" disabled={item.status==="resolved"}>Resolve</button><button data-feedback-id={item.id} data-feedback-action="note">Save note</button></div></article>)}</div>}</section>
    <section className="manager-content" id="reviews"><div className="content-heading"><div><span className="kicker">GOOGLE REVIEWS</span><h2>Review inbox</h2></div><span>{periodReviews.length} in this period</span></div>{reviews.length===0?<div className="manager-empty"><b>No Google reviews synced yet.</b><p>Connect Google and reviews from Search, Maps and StreetVouch will appear here.</p></div>:<div className="manager-list">{reviews.map(review=>{const suggestion=review.rating>=4?`Thank you ${review.reviewer_name??""} — we really appreciate your kind words and hope to see you again soon.`:"Thank you for the feedback. We’re sorry your visit did not meet expectations. Please contact the shop so we can understand what happened and put it right.";return <article className="manager-feedback review-item" key={review.id}><div className="feedback-top"><span className="stars">{"★".repeat(review.rating)}{"☆".repeat(5-review.rating)}</span><span>{review.reply_status==="published"?"replied":"reply needed"}</span><time>{new Date(review.google_created_at).toLocaleDateString("en-GB")}</time></div><p>{review.comment??"Rating only"}</p><div className="feedback-person"><b>{review.reviewer_name??"Google customer"}</b></div>{review.reply_status==="published"?<div className="published-reply"><b>Your reply</b><p>{review.reply_comment}</p></div>:<form className="review-reply" data-review-id={review.id}><label>Reply<textarea defaultValue={suggestion}/></label><button className="manager-primary" type="submit">Publish reply</button><span role="status"></span></form>}</article>})}</div>}</section>
  </main><Script src="/manager.js" strategy="afterInteractive"/></>;
}

function ManagerSignIn(){const linkStyle={color:"var(--ink)",fontWeight:800,textDecoration:"none"};return <><link rel="stylesheet" href="/manager.css"/><main className="manager-login"><div className="login-brand"><span>✓</span>streetvouch</div><div className="login-card"><img src="/village-barbers-logo.jpeg" alt="Village Barbers Cobham"/><span className="kicker">VILLAGE BARBERS COBHAM</span><h1>Manager sign in.</h1><p>Use the email address and password registered for this shop.</p><form id="manager-login"><label htmlFor="manager-email">Email address</label><input id="manager-email" type="email" required autoComplete="email" placeholder="you@example.com"/><label htmlFor="manager-password">Password</label><input id="manager-password" type="password" required autoComplete="current-password"/><div className="login-trap" aria-hidden="true"><input id="manager-website" tabIndex={-1} autoComplete="off"/></div><button type="submit">Sign in</button><p id="login-status" role="status"></p></form><nav aria-label="Account help" style={{display:"flex",justifyContent:"space-between",gap:16,borderTop:"1px solid var(--line)",paddingTop:18,marginTop:8,fontSize:14}}><a href="/manager/village-barbers-cobham/signup" style={linkStyle}>Create account</a><a href="/manager/village-barbers-cobham/forgot-password" style={linkStyle}>Forgot password?</a></nav></div><small>Private access for the Village Barbers Cobham management team.</small></main><Script src="/manager.js" strategy="afterInteractive"/></>}
function PasswordSetup(){return <><link rel="stylesheet" href="/manager.css"/><main className="manager-login"><div className="login-brand"><span>✓</span>streetvouch</div><div className="login-card"><img src="/village-barbers-logo.jpeg" alt="Village Barbers Cobham"/><span className="kicker">SECURE MANAGER ACCESS</span><h1>Choose a password.</h1><p>Use at least 10 characters, including a number. You’ll use this for everyday sign-in.</p><form id="manager-set-password"><label htmlFor="new-password">New password</label><input id="new-password" type="password" required minLength={10} autoComplete="new-password"/><label htmlFor="confirm-password">Confirm password</label><input id="confirm-password" type="password" required minLength={10} autoComplete="new-password"/><button>Save password</button><p id="login-status" role="status"></p></form></div></main><Script src="/manager.js" strategy="afterInteractive"/></>}
