import { env } from "cloudflare:workers";
import { headers } from "next/headers";
import { adminAllowed,db,json,sameOrigin } from "../../_shared";
import { emailOutcome } from "../../../../lib/operator";
type Row=Record<string,any>;
const escape=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export async function POST(request:Request){
 const h=await headers();if(!adminAllowed(h)||!sameOrigin(request))return json({message:'Operator access required.'},403);
 const d=db(),body=await request.json() as Row,b=await d.prepare('SELECT id,name,slug,report_email,contact_email,owner_email FROM businesses WHERE id=?').bind(body.businessId??'').first<Row>();if(!b)return json({message:'Business not found.'},404);
 if(!env.RESEND_API_KEY)return json({message:'Email delivery is not configured.'},503);
 const now=new Date().toISOString(),start=new Date(Date.now()-7*86400000).toISOString(),actor=h.get('oai-authenticated-user-email')!;
 let report:Row|null=null;
 if(body.reportId){report=await d.prepare("SELECT * FROM report_deliveries WHERE id=? AND business_id=? AND status='failed'").bind(body.reportId,b.id).first<Row>();if(!report)return json({message:'Only a failed report for this business can be retried.'},409);}
 const recipient=report?.recipient_email??b.report_email??b.contact_email??b.owner_email;
 if(!recipient||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(recipient))return json({message:'Add a valid report recipient to the business details.'},400);
 let snapshot:Row;
 if(report){try{snapshot=JSON.parse(report.snapshot);}catch{return json({message:'The saved report cannot be read. Generate a new summary.'},409);}}
 else {
 const [events,reviews,feedback]=await Promise.all([d.prepare('SELECT event_type,COUNT(*) count FROM events WHERE business_id=? AND created_at>=? GROUP BY event_type').bind(b.id,start).all<Row>(),d.prepare('SELECT COUNT(*) count,AVG(rating) average FROM google_reviews WHERE business_id=? AND google_created_at>=?').bind(b.id,start).first<Row>(),d.prepare("SELECT COUNT(*) count,SUM(CASE WHEN status!='resolved' AND contact_requested=1 AND contacted_at IS NULL THEN 1 ELSE 0 END) waiting,SUM(CASE WHEN severity!='normal' AND status!='resolved' THEN 1 ELSE 0 END) flagged FROM feedback WHERE business_id=? AND created_at>=?").bind(b.id,start).first<Row>()]);
 const counts=Object.fromEntries(events.results.map(r=>[r.event_type,r.count]));snapshot={pageVisits:counts.page_view??0,googleClicks:counts.google_click??0,privateMessages:feedback?.count??0,newGoogleReviews:reviews?.count??0,averageRating:reviews?.average??null,awaitingContact:feedback?.waiting??0,flagged:feedback?.flagged??0};
 }
 const id=report?.id??`weekly-${b.id}-${now.slice(0,10)}`,periodStart=report?.period_start??start,periodEnd=report?.period_end??now;
 const html=`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;padding:32px;color:#17312f"><p style="font-weight:bold">✓ streetvouch</p><h1 style="font-size:28px">${escape(b.name)} — weekly summary</h1><p>${escape(periodStart.slice(0,10))} to ${escape(periodEnd.slice(0,10))}</p><table style="width:100%;border-collapse:collapse">${Object.entries(snapshot).map(([key,value])=>`<tr><td style="padding:12px;border-bottom:1px solid #dce3df">${escape(key.replace(/([A-Z])/g,' $1'))}</td><td style="padding:12px;border-bottom:1px solid #dce3df;font-weight:bold">${escape(String(value??'No data'))}</td></tr>`).join('')}</table><p>Review the private inbox for context and next actions. No customer message content is included in this email.</p><p>Imported Google reviews may come directly from Search or Maps; review counts are not attributed to StreetVouch.</p><a style="display:inline-block;padding:14px 20px;background:#17312f;color:white;text-decoration:none;border-radius:8px" href="https://app.streetvouch.com/manager/${encodeURIComponent(b.slug)}">Open your owner portal</a></div>`;
 await d.prepare("INSERT OR IGNORE INTO operator_messages (id,business_id,kind,recipient,body,status,actor,created_at,updated_at) VALUES (?,?,'report',?,?,'draft',?,?,?)").bind(id,b.id,recipient,html,actor,now,now).run();
 const claim=await d.prepare("UPDATE operator_messages SET status='sending',updated_at=? WHERE id=? AND status IN ('draft','failed')").bind(now,id).run();if(!claim.meta.changes)return json({message:'This summary was already submitted today, or its delivery is being checked. Check its recorded status before sending again.'},409);
 let state='unknown',error:string|null='The email result is uncertain. Check the provider before retrying.',provider:string|null=null;
 try{const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':`sv-report-${id}`},body:JSON.stringify({from:env.EMAIL_FROM??'StreetVouch <notifications@mail.streetvouch.com>',to:[recipient],subject:`${b.name} — weekly customer summary`,html})});state=emailOutcome(r.status);if(state==='sent'){provider=((await r.json()) as Row).id;error=null;}else if(state==='failed')error='The email provider rejected this summary. Check the recipient and sender configuration.';}catch{}
 await d.batch([d.prepare('UPDATE operator_messages SET status=?,error=?,provider_id=?,updated_at=? WHERE id=?').bind(state,error,provider,new Date().toISOString(),id),d.prepare('INSERT INTO report_deliveries (id,business_id,recipient_email,status,period_start,period_end,error,snapshot,created_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,error=excluded.error').bind(id,b.id,recipient,state,periodStart,periodEnd,error,JSON.stringify(snapshot),now),d.prepare('INSERT INTO audit_events (id,business_id,actor_email,action,entity_type,entity_id,detail,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),b.id,actor,`report_${state}`,'report',id,`Weekly summary to ${recipient}`,now),...(state==='sent'?[d.prepare('UPDATE businesses SET last_report_sent_at=? WHERE id=?').bind(now,b.id)]:[])]);
 return json({message:state==='sent'?'Weekly summary accepted by the email provider.':error},state==='sent'?200:502);
}
